### ISSUE TITLE
EOUTOFMEMORY WITH SVG

### ISSUE THREAD

**Issue by phoenixfenix** [bgrabitmap/bgrabitmap#10]
Hello,

I attach the code to display the error EOutOfMemory.

Win 10 64bit ; Laz 1.6.4 64bit with FPC 3.0.2 and bgrabitmap 9.5

Thank you for every help

[TEST SVG2.zip](https://github.com/bgrabitmap/bgrabitmap/files/992422/TEST.SVG2.zip)

**Comment by circular17** [comment]
Hello,

I fixed the crash on the branch dev-bgrabitmap.

However, note that it occurs in a textPath (curved text) that is not yet supported by BGRASVG.

Regards

**Comment by phoenixfenix** [comment]
Hello,
Thank you for fixing !!!
