### ISSUE TITLE
Rendering of APNG (animated png)?

### ISSUE THREAD

**Issue by fredvs** [bgrabitmap/bgrabitmap#105]
Hello.

Does BGRABitmap deal with animated png (apng)?

![Animated_PNG_example_bouncing_beach_ball](https://user-images.githubusercontent.com/3421249/80915999-2b37c300-8d56-11ea-96ed-6054935ff1a1.png)

Huh, some old topic...
https://forum.lazarus.freepascal.org/index.php/topic,19764.0.html

Fre;D

**Comment by circular17** [comment]
Nope, it is not handled.

Apparently the format is very close to PNG.

So one could reuse existing code to make something like TBGRAAnimatedGif but for APNG.

**Comment by fredvs** [comment]
> Apparently the format is very close to PNG.

Imho, APNG is part of the PNG project.
https://en.wikipedia.org/wiki/APNG

> So one could reuse existing code to make something like TBGRAAnimatedGif but for APNG.

Ha, ok, BGRABitmap can work with animated gif already, wow I did not know that.
OK, I will take a look.

Thanks.

**Comment by fredvs** [comment]
By the way, if you know how to extract/add a image from/to a mp3 file, I am very interested.
All the fpc-delphi units that I did try was without luck.

Of course it exists utilities that does it, but direct access by code would be better.

**Comment by circular17** [comment]
I cannot help about mp3. Those are not trivial.

> Imho, APNG is part of the PNG project.
> https://en.wikipedia.org/wiki/APNG

Well yes and no. At least that's the impression I had reading through the details. That it has been derived from PNG that's for sure.

> Ha, ok, BGRABitmap can work with animated gif already, wow I did not know that.
> OK, I will take a look.

Yep. In fact, the main challenge for me was about the compression method.

**Comment by fredvs** [comment]
> I cannot help about mp3. Those are not trivial.

Decoding ID3Tags v 1 is a easy game, there  are in the first 128 bytes of the mp3.
But there is no image tag in v1.
You need decode ID3Tags v 2 and that is a other story.
Maybe because mp3 is open-source now that it will be easier to access it.

About animated png, I was surprised that GitHub can render-animate it.

**Comment by fredvs** [comment]
Hello.

I have found finally a way to extract image from  ID3Tags v 2.
Thanks to https://github.com/varianus/ovoplayer/tree/master/src/ovotag of @varianus.

It works perfectly for MSEgui too.

![strumpract_djtagimage](https://user-images.githubusercontent.com/3421249/124390765-4f41bc00-dced-11eb-8213-f69c2810c01b.png)

But it cannot animate the _apng_ included in the mp3 image-tag and only shows the first image with fpcimage_png.

So, if it could possible to render the animation with a BGRABitmap _apng_ renderer, it would be great.

**Comment by fredvs** [comment]
If by chance, it will be possible to render animated _apng_, one of the goal is to convert a short sequence of a video into a _apng_ .
For example with this converter-online https://ezgif.com/video-to-apng
Or maybe it exists desktop-converter that does it.

But of course, only applications that can animate _apng_ will show the video.
For all other mp3-players, they will see only the first image.

**Comment by fredvs** [comment]
Hello everybody.

Hum, some news?

**Comment by circular17** [comment]
Hi Fred,

I'm trying to implement it now. Hopefully I come back to you very soon.

Regards

**Comment by fredvs** [comment]
Genial!

And the good news is that, till now, no one media player can run-animate a (a)png.
All that I have try show only the first frame.
So we will be the first to show the animation.
The other good news is that _mp3_ is far from dead.
Even if _opus_ and _ogg_ files do it better (in theory), _mp3_ is still the most used format for internet.

Of course, in the _mp3_ tags, you are allowed to add all kind of custom files, even _mp4_ or _avi_ files.
But it is not the standard, usually there is only the "picture" tag that is checked by the media players.
And that picture tag must be in **PNG or JPEG** format ( and _apng_ is ok too but all the existing media players dont anim it, and _jpeg_ dont have a animated version, so no future for him).

**Comment by fredvs** [comment]
Re-hello.

To render the image tag of a mp3, I use a MSEImage + _LoadFromStream_(). 

`amseimage.bitmap.LoadFromStream(TagReader.Tags.Images[0].Image);`

But it does like other png-reader, it only shows the first frame of the _apng_ saved into the mp3.

**Comment by DomingoGP** [comment]
Hello.

Recently I have implemented it, but requires libpng.dll.

[testAPNG.zip](https://github.com/bgrabitmap/bgrabitmap/files/13257676/testAPNG.zip)

Best regards.
Domingo.

**Comment by fredvs** [comment]
Hello Domingo.

Fantastic!

Sadly I dont have a Windows machine to test it at the moment.
On Linux, I get those error messages (see picture).

![apng_test_linux_error](https://github.com/bgrabitmap/bgrabitmap/assets/3421249/a0843f05-2a48-4d49-9f2b-5aad376d7cec)

Surely I miss to install a package but I dont know if it is from BGRABitmap or a other Linux unit is missing.

Fre;D

**Comment by DomingoGP** [comment]
You can try to uncomment the line 355 of libPngDllWrap.pas
//  size_t = ptruint; 

I guess this will solve the errors, I can't test on linux.

Domingo.

**Comment by fredvs** [comment]
Hello Domingo.

> You can try to uncomment the line 355 of libPngDllWrap.pas
> // size_t = ptruint;

Yep, indeed, the compilation is ok now.

But at running there is that error message (see picture):

![apng_test_linux_error2](https://github.com/bgrabitmap/bgrabitmap/assets/3421249/c85758e0-1812-4594-99f3-a6090723acfc)

I did try to load other png from your demo but same error.

Fred.

**Comment by fredvs** [comment]
Re-hello Domingo.

With debugging on, there is that error at loading:

![apng_test_linux_error3](https://github.com/bgrabitmap/bgrabitmap/assets/3421249/35d3e1b4-e605-4683-bcb3-66bf807febc3)

**Comment by DomingoGP** [comment]
Can you try to change the line 355 of libPngDllWrap.pas to.
  size_t = png_uint_32;

Your CPU is 32 or 64 bits?

I'm sorry it doesn't work for you, I should have tested it on other systems before sending it.

**Comment by DomingoGP** [comment]
If the previus change don't work you can try to include ctypes in uses clause
and change the line 355 to
 size_t = csize_t;

**Comment by fredvs** [comment]
Hello Domingo.

>Can you try to change the line 355 of libPngDllWrap.pas to.
>size_t = png_uint_32;

I did change but still same error.

> Your CPU is 32 or 64 bits?

It is 64 bit from XUbuntu LTS 22.04.

>If the previus change don't work you can try to include ctypes in uses clause
>and change the line 355 to
>size_t = csize_t;
 
I did try with this too but same error.

>I'm sorry it doesn't work for you, I should have tested it on other systems before sending it.

Ho, I am more than happy that something move for apng.
The wish date from more than 10 years ago (February 01, 2013, 09:03:54 pm)!:
https://forum.lazarus.freepascal.org/index.php/topic,19764.0.html

So it is already a big step if it works for Windows.
Many thanks for that.

Fred.

**Comment by circular17** [comment]
Hi Fred and Domingo,

It is an interesting approach to use `libpng`. One the one hand, there is less coding because there library does most of the processing, one the other hand, the dependency may change depending on the platform and the configuration of the system.

I reckon the initial query dates back a long time ago. There are a plethora of requests for BGRABitmap and LazPaint. It shows that people use them, that's heartwarming. For a long time, I've been developing most of them, but these days, people have contributed. That's less of a mountain for me to do and also I am less alone in this journey.

On my side, I've take the path of implemented animated PNG in BGRABitmap and it seems to be fruitful. Now, animated PNG can be loaded frame by frame via the readers and writers of PNG.

The `TBGRAAnimatedGif` makes it even easier. This class can load and save both GIF and animated PNG, furthermore it can display and animate them on a canvas.

It can convert between those formats, but some files cannot be saved directly from one format to the other due to some minor differences. I've added some comments in the `BGRAAnimatedGif` unit with all the details.

The tests for PNG provided on the following page seem to be render harmoniously: https://philip.html5.org/tests/apng/tests.html

The following online tool to check PNG chunks has been an invaluable help in debugging:
https://www.nayuki.io/page/png-file-chunk-inspector

I've improved the application in BGRABitmap test folder to read and write both GIF and PNG, and display some information about the file:
https://github.com/bgrabitmap/bgrabitmap/tree/dev-bgrabitmap/test/testgif

It is on the `dev-bgrabitmap` branch.

Enjoy!

**Comment by fredvs** [comment]
Johann: WOOOOW.

I will deeply study your marvelous code tonight.

Write you later.

XXXXL Thanks.

Fre;D

**Comment by fredvs** [comment]
Hello Circular.

>I've improved the application in BGRABitmap test folder to read and write both GIF and PNG, and display some information about the file:
>https://github.com/bgrabitmap/bgrabitmap/tree/dev-bgrabitmap/test/testgif

Perfect and out-of-the-box.
Like always with you: I am hyper-impressed.
Congratulationssss.

Tonight I will try to do it for msegui, extracting the image tag from a mp3.
At the moment I use (of course with only first frame) this:

`amseimage.bitmap.LoadFromStream(TagReader.Tags.Images[0].Image);`

(Hum, a lazy-question, I must study your code, but maybe you have some advice how to convert this using BGRABitmap and render the anim?)

**Comment by circular17** [comment]
Hi Fred,

It is heartwarming to hear your enthousiasm. Indeed I like "out-of-the-box" programs, as you've aptly describe them. Now I am thinking about cats, who like to play with boxes :D More seriously, I had the inspiration for this development, and in particular I've been motivated by @DomingoGP contributions and **r.lukasiak** plans on doing videos with AVIF.

Regarding the animation of mp3 meta-information, I am not sure what your question is about. `TBGRAAnimatedGif` can read from a stream. Maybe it doesn't work directly in mseGUI?

Warm regards

**Comment by fredvs** [comment]
Hello Johann and Domingo.

BGRABitmap is the top with this video/anims feature.

>Regarding the animation of mp3 meta-information, I am not sure what your question is about. TBGRAAnimatedGif can read from a stream.

Ha, ok there is also _bitmap.LoadFromStream()_ with BGRABitmap, perfect.  ;-)

>Maybe it doesn't work directly in mseGUI?

I did not test yet, but I am sure it will work.

@DomingoGP : many thanks too for your great contributions.

Fre;D

**Comment by fredvs** [comment]
Hello.

I try to make apng work for msegui but I fail.

I dont get how to do to show the frames without animation.
I will do the timer-anim later.

At the moment I have this that compiles but nothing is shown:

```
unit main;
{$ifdef FPC}{$mode objfpc}{$h+}{$endif}

interface

uses
 BGRABitmap, BGRAAnimatedGif, types,
  msetypes, mseglob, mseguiglob, mseguiintf, mseapplication, msestat, msemenus,
  msegui,msegraphics, msegraphutils, mseevent, mseclasses, msewidgets, mseforms,
  mseimage;

type
 tmainfo = class(tmainform)
   aimage: TBGRAAnimatedGif;   
   procedure oncreatedform(const sender: TObject);
   procedure onpaintform(const sender: twidget; const acanvas: tcanvas);
 end;

var
 mainfo: tmainfo;

implementation

uses
  main_mfm;
 
procedure tmainfo.oncreatedform(const sender: TObject);
begin
 aimage := TBGRAAnimatedGif.Create('waterdrops.png');
 width := aimage.Width;
 Height := aimage.Height;
end;

procedure tmainfo.onpaintform(const sender: twidget; const acanvas: tcanvas);
var
 arect: Trect;
begin
 arect.Height := Height;
 arect.width := width;
 aImage.Show(aCanvas, arect);        
 // aImage.update(aCanvas, arect);   
end;

end.
```

If I use 

```
aimage : TBGRABitmap;

aimage := TBGRABitmap.Create('waterdrops.png');

aImage.draw(aCanvas, 0,0);        

```

The first frame is shown.
But I dont understand how to show the frames with TBGRAAnimatedGif.

;-(

**Comment by circular17** [comment]
Hi Fred,

To animate, you need to use a timer and call periodically the `Update` function. On Windows and Linux, you can have the following steps:
- in the Paint event, call the function `Show`, it will initially display the image
- enable a timer to be triggered for example every 15 ms
- in the timer event, if the image has already been show, call the `Update` function

On MacOS, this won't work because painting cannot happen outside of the Paint event. That's why the code of the `testgif` sample program define a custom control to do that.

Alternatively, you can simply redraw the area regularly by using the `MemBitmap` property, which contains the current frame (it changes over time).

Regards

**Comment by fredvs** [comment]
Hello Jo.

OK, I understood that a timer is needed to do the animation.

But I dont get how to show the frames "statically" for example to show the first or last frame, without any timer.

I will try with _MemBitmap_.

By the way, I did a little change in _bgraanimatedgit.pas_ to be compatible with msegui, line 1040:

Changing this:

 `copy := MemBitmap.MakeBitmapCopy(clsilver, true);`

with this

 `copy := MemBitmap.MakeBitmapCopy(TColor($C0C0C0), true);
`

This because clsilver is not defined in msegui.
But this is detail.

**Comment by fredvs** [comment]
Re-hello.

Yep, _MemBitmap_ do the trick statically.

and using this do the animation without timer (but not the right way, I know, it is for testing).

```
procedure tmainfo.onpaintform(const sender: twidget; const acanvas: tcanvas);
var
 arect: Trect;
begin
 arect.Height := Height;
 arect.width := width;
 aImage.MemBitmap.draw(aCanvas, 0,0);   
 aImage.update(aCanvas, arect);  
 Invalidate;   
end;


```
The background is black, surely I have to define it before.

![mse_apng](https://github.com/bgrabitmap/bgrabitmap/assets/3421249/dab49658-db35-41c9-a581-e6ab6b2bae11)

Perfect, I have all the keys, big congrats.

I will attack the timer...

**Comment by fredvs** [comment]
Re-re hello.

I try to make the animation work with the timer but have bad result.

Here is the code I used:

```
unit main;
{$ifdef FPC}{$mode objfpc}{$h+}{$endif}
interface
uses
 BGRABitmap, BGRAAnimatedGif, types,msetypes, mseglob, mseguiglob, mseguiintf,
  mseapplication, msestat, msemenus,msegui,msegraphics, msegraphutils, mseevent,
  mseclasses, msewidgets, mseforms,mseimage, msetimer;

type
 tmainfo = class(tmainform)
   aimage: TBGRAAnimatedGif;   
   ttimer1: ttimer;
   procedure oncreatedform(const sender: TObject);
   procedure onpaintform(const sender: twidget; const acanvas: tcanvas);
   procedure ontime(const sender: TObject);
 end;

var
 mainfo: tmainfo;
 arect: Trect;
 isfirst: boolean = true;

implementation

uses
  main_mfm;
 
procedure tmainfo.oncreatedform(const sender: TObject);
begin
 aimage := TBGRAAnimatedGif.Create('waterdrops.png');
 width := aimage.Width;
 Height := aimage.Height;
 arect.Height := Height;
 arect.width := width;
 ttimer1.enabled := true;
end;

procedure tmainfo.onpaintform(const sender: twidget; const acanvas: tcanvas);
var
 brect: rectty;
begin
 brect.x := 0;
 brect.y := 0;
 brect.cx := width;
 brect.cy := Height;
 aCanvas.FillRect(brect, cl_yellow);  
 aImage.show(acanvas, arect);
end;

procedure tmainfo.ontime(const sender: TObject);
begin
 if isfirst then aImage.show(mainfo.getcanvas, arect) else  
 aImage.update(mainfo.getcanvas, arect) ;
 isfirst := false;
end;

end.
```

The anim works but dont erase the previous frame.
Sure I dont catch something (but what).

![mse_apng2](https://github.com/bgrabitmap/bgrabitmap/assets/3421249/9cf0bbf2-bd46-4d8d-9f3b-8096cb96b5c3)

**Comment by fredvs** [comment]
Re-re Hello.

Allez, this time better news.

But I get good result only using a independent thread and without timer ( instead  there is a  "sleep" in thread.execute ).

```
unit main;
{$ifdef FPC}{$mode objfpc}{$h+}{$endif}
interface
uses
 BGRABitmap, BGRAAnimatedGif, sysutils, types,msetypes, mseglob, mseguiglob, msethread,
 mseguiintf,mseapplication, msestat, msemenus,msegui,msegraphics,msegraphutils,
 mseevent,mseclasses, msewidgets, mseforms,mseimage, msetimer,msesimplewidgets;

type
 tmainfo = class(tmainform)
   aimage: TBGRAAnimatedGif;   
   procedure oncreatedform(const sender: TObject);
   procedure onpaintform(const sender: twidget; const acanvas: tcanvas);
   procedure InvalidateImage;
   
   protected
   thethread: tmsethread;
   function Execute(thread: tmsethread): integer;

 end;

var
 mainfo: tmainfo;
 x : integer = 0;
 
implementation

uses
  main_mfm;
 
procedure tmainfo.oncreatedform(const sender: TObject);
begin
 aimage := TBGRAAnimatedGif.Create('waterdrops.png');
 width := aimage.Width;
 Height := aimage.Height;
 thethread    := tmsethread.Create(@Execute);
 caption := 'apng demo';
end;

procedure tmainfo.onpaintform(const sender: twidget; const acanvas: tcanvas);
var
 arect: Trect;
 brect: rectty;
begin
 arect.Height := Height;
 arect.width := width;
 brect.x := 0;
 brect.y := 0;
 brect.cx := width;
 brect.cy := Height;
 aCanvas.FillRect(brect, color);  
 aImage.show(acanvas, arect);
end;

procedure tmainfo.InvalidateImage;
begin
  onpaintform(mainfo, getcanvas);
end;

function tmainfo.Execute(thread: tmsethread): integer;
begin
  result := 0;
  repeat
   application.queueasynccall(@InvalidateImage);
   sleep(150);
  until false;
end;

end.
```

Also it does not use aImage.update(), if using it, the frames are not ok (see previous post).
Surely it is not the best way but it works ok (see animation).
 
https://github.com/bgrabitmap/bgrabitmap/assets/3421249/afe7c44f-d16e-4734-9a97-42e005a27ced

**Comment by circular17** [comment]
Hi Fred,

The attempt https://github.com/bgrabitmap/bgrabitmap/issues/105#issuecomment-1793864648 you've made with a yellow background  is correct but I suppose the background cannot be retrieved correctly. To circumvent this problem you can use another `BackgroundMode`. In this case `gbmEraseBackground` and set `EraseColor` property to your background color, here `clYellow`.

```pascal
  //how to deal with the background under the GIF animation
  TGifBackgroundMode = (
    gbmSimplePaint,                   // frames are rendered without clearing the backgroud
    gbmEraseBackground,               // pixels in the GIF that become transparent are filled with EraseColor
    gbmSaveBackgroundOnce,            // background is saved once before drawing the first frame
    gbmUpdateBackgroundContinuously); // background is updated continuously to handle overlapping animations
```

Also you don't need the `firstTime` boolean here because the timer is supposed to be called after the first paint.

It is also possible to refine the timer interval so that it corresponds to the actual time until the next frame.

So the code would become:
```pascal
unit main;
{$ifdef FPC}{$mode objfpc}{$h+}{$endif}
interface
uses
 BGRABitmap, BGRAAnimatedGif, types,msetypes, mseglob, mseguiglob, mseguiintf,
  mseapplication, msestat, msemenus,msegui,msegraphics, msegraphutils, mseevent,
  mseclasses, msewidgets, mseforms,mseimage, msetimer;

type
 tmainfo = class(tmainform)
   aimage: TBGRAAnimatedGif;   
   arect: Trect;
   ttimer1: ttimer;
   procedure oncreatedform(const sender: TObject);
   procedure onpaintform(const sender: twidget; const acanvas: tcanvas);
   procedure ontime(const sender: TObject);
 end;

var
 mainfo: tmainfo;

implementation

uses
  main_mfm;
 
procedure tmainfo.oncreatedform(const sender: TObject);
begin
 aimage := TBGRAAnimatedGif.Create('waterdrops.png');
 aimage.BackgroundMode := gbmEraseBackground;
 aimage.EraseColor := Color; // assign the actual color of the form
 width := aimage.Width;
 Height := aimage.Height;
 arect.Left := 0;
 arect.Top := 0;
 arect.Height := Height;
 arect.width := width;
 ttimer1.enabled := false;
end;

procedure tmainfo.onpaintform(const sender: twidget; const acanvas: tcanvas);
var
 brect: rectty;
begin
 brect.x := 0;
 brect.y := 0;
 brect.cx := width;
 brect.cy := Height;
 aCanvas.FillRect(brect, cl_yellow);  
 aImage.show(acanvas, arect);
 ttimer1.enabled := true; // enable timer here
end;

procedure tmainfo.ontime(const sender: TObject);
begin
 ttimer1.enabled := false;
 aImage.update(mainfo.getcanvas, arect) ;
 ttimer1.interval := aImage.TimeUntilNextImageMs; // wait until next frame needs to be drawn
 ttimer1.enabled := true;
end;

end.
```

**Comment by fredvs** [comment]
Last shadow, is it possible to know if the _png_ is animated or _"simple png_"?
Maybe with _aimage.count_ ?

Is it ok then to use always a _TBGRAAnimatedGif_ even if the _png_ is not animated?

**Comment by fredvs** [comment]
Hello...

Regarding animated png, I try, using previous code, to do it via a steam (for later use the one from a mp3 image tag).

For this, I try to adapt the code to use a stream vs the png file with this:

```
procedure tmainfo.oncreatedform(const sender: TObject);
var 
  m: TStream;
  streamimage: TBGRAAnimatedGif;   

begin
 streamimage := TBGRAAnimatedGif.Create('waterdrops.png');  // the original png file

 m := TStream.create;
 streamimage.SaveToStream(m);   // the original png file saved as stream --> crash
 
 aimage := TBGRAAnimatedGif.Create(m);  // the aimage that is used in all the code from m stream

....
```
 
It compiles but at run there is a crash when trying to _streamimage.SaveToStream(m);_  with error:

```
An unhandled exception occurred at $00000000004F5404 :
Exception : Draw mode not supported by GIF
  $00000000004F5404
  $00000000004F6127
```
 
What is wrong?

**Comment by DomingoGP** [comment]
Hi Fred, 

I thing you should use a TMemoryStream instead of a TStream.
I guess this code will work for You. (not tested).

```
procedure tmainfo.oncreatedform(const sender: TObject);
var 
  m: TMemoryStream;
  streamimage: TBGRAAnimatedGif;   

begin
 streamimage := TBGRAAnimatedGif.Create('waterdrops.png');  // the original png file

 m := TMemoryStream.create;
 streamimage.SaveToStream(m);   // the original png file saved as stream --> crash
 m.Position:=0;   //<<<<<<<<<<<<<<<<< rewind stream.
 aimage := TBGRAAnimatedGif.Create(m);  // the aimage that is used in all the code from m stream

```

Best Regards 
Domingo

**Comment by fredvs** [comment]
Hello Domingo.

I have try also with Tmemorystream and with your code.
It compiles ok but at run there is the same error at "streamimage.SaveToStream(m);"

```
An unhandled exception occurred at $00000000004F5424 :
Exception : Draw mode not supported by GIF
  $00000000004F5424
  $00000000004F6147

```

**Comment by fredvs** [comment]
Re-hello.

I did try to use directly the stream from a mp3 image tag.
The code is like this:
```
          if assigned(infosdfo.aimage) then infosdfo.aimage.free;
           infosdfo.aimage := TBGRAAnimatedGif.Create(TagReader.Tags.Images[0].Image);
           infosdfo.aimage.BackgroundMode := gbmEraseBackground;
           infosdfo.aimage.EraseColor := Color; // assign the actual color of the form
```

But using this code (following Circular example) shows the first frame only with _aImage.MemBitmap.draw(acanvas, 0,0)_; 

```
procedure tinfosdfo.onpaintimg(const sender: twidget; const acanvas: tcanvas);
var
 brect: rectty;
 arect: trect;
begin
 arect.width := PimgPreview.width;
 arect.height := PimgPreview.height;
 brect.x := 0;
 brect.y := 0;
 brect.cx := arect.width;
 brect.cy := arect.height;
 aCanvas.FillRect(brect, cl_yellow);  
 
 aImage.MemBitmap.draw(acanvas, 0,0);  // using this shows first frame

 //aImage.show(acanvas, arect);  // using this dont show nothing
 
 ttimer1.interval := aImage.TimeUntilNextImageMs ; // wait until next frame needs to be drawn
 ttimer1.enabled := true; // enable timer here
end;
```

It seems that _aImage.show(acanvas, arect)_ does not work with the stream (or I miss something).

The good news is that the stream from mp3 is accepted by BGRABitmap.

Fre;D

**Comment by circular17** [comment]
When you save to a stream, you need to specify the image format as an additional parameter, `ifPng`, otherwise it will try to save it as Gif.

**Comment by fredvs** [comment]
Hello.

I try this: 

`streamimage.SaveToStream(m,ifPng);`

But error at compile:

`Error: Identifier not found "ifPng"`

**Comment by fredvs** [comment]
Re-hello.

OK,ok, ok, _BGRABitmapTypes_ was missing in uses section.

Now it compiles and the animation is perfect too with the stream.
Also  _aImage.show(acanvas, arect)_ works with Circular-adapted-for-stream code.

I dont know why _aImage.show(acanvas, arect)_ does not work with the mp3 stream.
Maybe the solution will appear a other day.

**Comment by fredvs** [comment]
EXCELLENT!

Dream comes true.
https://github.com/bgrabitmap/bgrabitmap/assets/3421249/9ba60a46-0f25-47e4-890c-7d3f24308cb0

Many, many, many thanks Johann.

**Comment by circular17** [comment]
Looks very nice. Well done!

**Comment by fredvs** [comment]
You well done!

I like this apng:
![guitar](https://github.com/bgrabitmap/bgrabitmap/assets/3421249/f852547f-d04a-4057-a235-ebf72769c782)

Here a test mp3 with the image tag of png above:
[test.mp3.zip](https://github.com/bgrabitmap/bgrabitmap/files/13313094/test.mp3.zip)

Now all the art will be to create short apng, with fluid loop, to not blow up the mp3's.

**Comment by circular17** [comment]
Cool, when I open it on MacOS I can see the image. It is not animated but at least it shows up and it can be animated if the reader supports it!

I suppose you've thought of the same about creating small animated images: reducing the FPS and the size or the color count. About graceful looping, I only can think of reversing the time. Otherwise, I don't see any easy way of making it loop, apart maybe using IA image generation.

Happy PNG-ing!

**Comment by fredvs** [comment]
Note that, strangely,  _aImage.show(acanvas, arect)_ does not work, it is not triged when I adapted your code for the _StrumPract_ project.
Maybe because there are too many threads working together, I dont know.

Anyway, luckily, _aImage.MemBitmap_  works like charm with this adaptations and the transparency is preserved + stretching ok:

```
procedure tinfosdfo.onpaint_img(const Sender: twidget; const acanvas: tcanvas);
var
  theMemBitmap: TBGRABitmap;
begin
  theMemBitmap := aimage.MemBitmap.Resample(PimgPreview.Width, PimgPreview.Height, rmFineResample) as TBGRABitmap;
  theMemBitmap.Rectangle(0, 0, PimgPreview.Width, PimgPreview.Height, BGRA(255, 192, 0), BGRA(180, 180, 180, 255), dmDrawWithTransparency, 8192);
  theMemBitmap.draw(acanvas, 0, 0, True);
  theMemBitmap.Free;
end;
```

And the animation is done by a timer set to 130 ms.
The timer is enabled _if aimage.count > 0_

```
procedure tinfosdfo.ontime(Sender: TObject);
begin
  PimgPreview.invalidate;
  //ttimer1.interval := aImage.TimeUntilNextImageMs; // does not work, alway result = 0
end;
```

Strangely no aImage.update is needed to have the next frame.

I did compare the result with your demo code with mono thread that uses  _aImage.show(acanvas, arect)_ and I did not feel difference.

If it is not a crime to use Bitmap.draw() vs aImage.show(), I am totally happy.

**Comment by fredvs** [comment]
> apart maybe using IA image generation.

Hum, I forgot this one.
Maybe. (or maybe not).

**Comment by circular17** [comment]
Hi Fred,

> If it is not a crime to use aImage.Bitmap.draw() vs aImage.show(), I am totally happy.

Nope, you won't go to court for that. In fact, the `aImage.show` method is provided as a helper to make life easier when rendering on a canvas, but otherwise using `aimage.MemBitmap` is the way to go when working with `TBGRABitmap` objects. The `aImage.update` method only makes sense when you've used `aImage.show` before and that the background has not been cleared.

About the `TimeUntilNextImageMs` property being equal to zero, it means that the image needs to be rendered immediately. In this case, I suppose it is because the call to `invalidate` doesn't actually redraw the image, it is done later when the form is updated. Instead what you can do is disable the timer, and when you actually have painted the image, set the interval and enable the timer again.

Note that it could happen that the value of `TimeUntilNextImageMs` is zero anyway if the next frame is immediately afterwards, so you need to check this. For example you can load the value into a variable, and if it is less than 15, set it to 15 ms.

Regards

**Comment by fredvs** [comment]
>Note that it could happen that the value of TimeUntilNextImageMs is zero anyway if the next frame is immediately afterwards, so you need to check this. For example you can load the value into a variable, and if it is less than 15, set it to 15 ms.

Ok, done, many thanks.

Fre;D

**Comment by fredvs** [comment]
Re-hello.

OK, I think I found the solution.

In **bgramseguibitmap.pas**, at line 30, add this:

```
 { TBGRAMSEguiBitmap }

  TBGRAMSEguiBitmap = class(TBGRADefaultBitmap)
  protected
  ...
 public
    procedure AssignToBitmap(ADestination: TBitmap);  // add this
 ...
```

And a few later, at line 70 add this:

```
{ TBGRAMSEguiBitmap }

procedure TBGRAMSEguiBitmap.AssignToBitmap(ADestination: TBitmap);
begin
  ADestination.Assign(Bitmap);
end;
```

 With those change the compilation is ok on Windows and the animated png is dancing lovely, like in Linux/BSD OS.

;-)
