### ISSUE TITLE
Load/save DPI setting of images

### ISSUE THREAD

**Issue by circular17** [bgrabitmap/bgrabitmap#109]

**Comment by maxm74** [comment]
I'm working on it in core components (bgrabitmap repository)

**Comment by circular17** [comment]
I suppose it is the following pull request?
https://github.com/bgrabitmap/bgrabitmap/pull/203

**Comment by maxm74** [comment]
Yes but I closed it because I'm still working on it. Tif and Jpeg will be supported in the coming days.

**Comment by circular17** [comment]
Cool

**Comment by maxm74** [comment]
take a look to pull request  #205

**Comment by maxm74** [comment]
I Think can be closed, solved.
