### ISSUE TITLE
Problem with unicode fonts

### ISSUE THREAD

**Issue by lainz** [bgrabitmap/bgrabitmap#11]
https://forum.lazarus.freepascal.org/index.php/topic,24176.msg259560.html#msg259560
https://forum.lazarus.freepascal.org/index.php/topic,24176.msg259587.html#msg259587

Seems that one of the draw text methods doesn't handle unicode.

**Comment by lainz** [comment]
Tested. The problem is with TextOut, in the other hand TextRect seems to works fine.

**Comment by circular17** [comment]
Does not seem like I can reproduce the bug.

Is there something I am missing?

[testunicode.zip](https://github.com/bgrabitmap/bgrabitmap/files/1700714/testunicode.zip)

![testunicode](https://user-images.githubusercontent.com/9092455/35883028-39486228-0b86-11e8-9e25-fd893d135b32.png)

**Comment by lainz** [comment]
Hi, this bug is older than Lazarus 1.8, meant to be reproduced with 1.6 I think, but it has no sense to test it against an older version of Lazarus now.

Thinking that, the thing was actually a LCL or Lazarus bug, that was fixed in 1.8.

**Comment by lainz** [comment]
Hi, new info here:
http://forum.lazarus.freepascal.org/index.php/topic,24176.msg275620.html#msg275620

Seems that this bug is with a specific font.

**Comment by circular17** [comment]
Ok so not much I can do on BGRABitmap side. Thanks!

**Comment by lainz** [comment]
Yes, in fact TCanvas has the bug, fonts with missing glyphs doesn't work either. But seems that the system drawing of text (like in TLabel or TButton) uses a fallback font if the font you provide is not complete, so it draws with 2 or more fonts perfectly all text.

As discussed in the forum TCanvas maybe can't be fixed also, since it already uses the OS implementation.

**Comment by lainz** [comment]
Hi again, sorry for bothering you, in the forum explained this:

On Windows, TextOutW (and its variations) uses the supplied font, while DrawTextW does font substitution for missing glyphs.

So maybe that can be used to fix the problem?

**Comment by circular17** [comment]
I am opening back this issue until I examine this topic. Regards

**Comment by lainz** [comment]
Thanks. See you!

**Comment by circular17** [comment]
This problem is probably solved in dev branch. Lainz, can you confirm this?

**Comment by circular17** [comment]
Cool. Thanks for testing.
