### ISSUE TITLE
Compilation of BGRAFreeType fails with Lazarus 2.0 fixes branch

### ISSUE THREAD

**Issue by BugsBeGone** [bgrabitmap/bgrabitmap#112]
Commit [7420aef9](https://github.com/bgrabitmap/bgrabitmap/commit/7420aef93096820fe797b18b79938d230f1bb07a) relies on Lazarus trunk commit [r63145](https://github.com/graemeg/lazarus/commit/89caffdc9e6ca8d968701ef5c70f41df0b87f375), which has not yet been included in any releases or stable branches. The `$DEFINE` to enable the new kerning checks against 2.0.9, which is the current version for the Lazarus 2.0 fixes branch.

I would suggest changing this to check against 2.1.0, which will still fail to compile against outdated checkouts, but anyone relying on Lazarus trunk will have bigger problems to deal with.

Also, I'm not entirely sure if moving `{$DEFINE LAZFREETYPE_GLYPH_BOX_FIXED}` inside the version check was intended either. Unrelated to this issue, but changing the version alone will possibly break that functionality without moving it first.

**Comment by circular17** [comment]
Oh ok thanks. I was wondering about the version number. So better check against 2.1.0. 

Regarding the glyph boxes, they are buggy in 2.0.8, so the algorithm cannot use them fully. They are fixed on trunk along with the new kerning.

**Comment by BugsBeGone** [comment]
Ah okay, so both should definitely be inside the same version check. Will update the PR to remove the extra unnecessary commit.

**Comment by circular17** [comment]
Thanks. Just merged the branch.

**Comment by BugsBeGone** [comment]
I can't really show, but I can describe. Essentially machine vision, so taking camera images and visualising several metrics by drawing directly on top. Used to be done with TCanvas etc. which was fine for smaller images, but became very slow when we upgraded to a 5MP sensor.

**Comment by circular17** [comment]
Interesting. I wonder which kind of procedures were slower with TCanvas?
