### ISSUE TITLE
Darwin64 and Qt5 inverted colors

### ISSUE THREAD

**Issue by lainz** [bgrabitmap/bgrabitmap#12]
{$DEFINE BGRABITMAP_RGBAPIXEL}
That define according to @esvignolo is wrong. He tested it on his Mac.

This also solves LazPaint color issues on Mac.

**Comment by circular17** [comment]
Hmm.. I don't understand because I remember testing it on MacOS. Could it be that it depends on the version of MacOS? See: http://forum.lazarus.freepascal.org/index.php/topic,24239.msg228750.html#msg228750

**Comment by lainz** [comment]
It is MacOS but also it is Qt5, maybe for that?
@esvignolo offered his machine to test it with TeamViewer if you want, you can contact him on Facebook, is already your friend Esteban Vignolo.

**Comment by esvignolo** [comment]
Yes in macos (carbon) a time ago, has the same problem and @circular17 fix it. But this is in macos QT5.

**Comment by circular17** [comment]
So could we use some $IFDEF to check if it is QT5, or any QT?

**Comment by esvignolo** [comment]
I only try with QT5, I don't see any conditional for QT, but, I remove the {$DEFINE BGRABITMAP_RGBAPIXEL} and work fine.

**Comment by circular17** [comment]
I guess it is with all version of QT. What about the following?
`{$IFDEF DARWIN} `
 `  {$IFNDEF LCLQt} `
 `     {$DEFINE BGRABITMAP_RGBAPIXEL} `
 `  {$ENDIF} `
 `{$ENDIF} `

**Comment by esvignolo** [comment]
Yes, I think that's enough.

**Comment by circular17** [comment]
This works for you?

**Comment by lainz** [comment]
In the package options maybe using -dBGRABITMAP_BGRAPIXEL is enough, since that avoids defining RGBA order and changing the files.

**Comment by circular17** [comment]
That would be possible. However that implies the user to do something. That's ok for me to change some files.

**Comment by circular17** [comment]
I pushed the change on dev-bgrabitmap. @esvignolo can you confirm it works for you?

**Comment by lainz** [comment]
Hi @circular17, @esvignolo told me yesterday that was not working, but wait confirmation from him.
Is strange, these defines looks well.

**Comment by lainz** [comment]
Hi, I tested it

**Comment by lainz** [comment]
Tested some more apps and has the issue of colors even if there's the setting applied.
I will try with cocoa, not qt.
