### ISSUE TITLE
Custom letter kerning/spacing

### ISSUE THREAD

**Issue by circular17** [bgrabitmap/bgrabitmap#123]
https://forum.lazarus.freepascal.org/index.php/topic,51266.msg376076.html#msg376076

Hi!

There are situations where you want to control the kerning of some text as you now it from all the Desktop Publishers. 
This means: Make the distance between the letters smaller or wider.

BGRAbitmap has not a straight solution. Only a diffused trick: 
TextOutCurved has the parameter 
ALetterSpacing: single

We "missuse" that. The Path wich is needed  by TextOutCurved is only made of 2 points: 
Beginning and ending of the text.

**Comment by circular17** [comment]
added TextOut with letter spacing parameter on dev branch.

**Comment by Alexey-T** [comment]
Thanks...
