### ISSUE TITLE
TextOut variant is needed - to render using Dx offsets array (distance between chars)

### ISSUE THREAD

**Issue by Alexey-T** [bgrabitmap/bgrabitmap#125]
Like here
 function ExtTextOut(DC: HDC; X, Y: Integer; Options: Longint; Rect: PRect; Str: PChar; Count: Longint; Dx: PInteger): Boolean;

https://wiki.freepascal.org/lclintf

**Comment by circular17** [comment]
There are some caveats to that. For example what happens if the supplied string contains nonspacing marks. For example, instead of "â" the combination "a" + "^" (0302). In this case, is there an offset fo the nonspacing mark "^"?

Note: On dev branch, I've added TGlyphCursorUtf8 record that can be used to browse the glyphs, taking into account nonspacing marks and also multichar combination "lam" + "aleph". The function you are asking for would be similar to TBGRADefaultBitmap.InternalTextOutLetterSpacing except that the letter spacing would come from an array.

**Comment by Alexey-T** [comment]
Afair, win32 api applies dx offset to each char, even for accent char, so to render letter+accent in one place, I must make 2 special offsets

**Comment by circular17** [comment]
Hmmm, so for example "ba^c" would go with an array (20, 0, 20, 20) to make "bâc" where letters are evenly placed?

As I would render each multichar "b" then "â" then "c", then the actual offset would be the sum of the offsets of the multichar. So 0+20 for the offset between "â" and "c".

I don't have Windows to check, I will check on MacOS and see.

**Comment by circular17** [comment]
On MacOS, it seems that "a^" is considered as one character. Also tested with "lam" + "aleph" and in this case, the offsets are added for both characters.

```
uses LCLType, LCLIntf, BGRAUTF8;

{ TForm1 }

procedure TForm1.FormPaint(Sender: TObject);
const ETO_PDY = $2000;
var
  dx: packed array[0..5] of integer;
  testText: string;
  r: TRect;
begin
  r := Rect(0,0,ClientWidth,ClientHeight);
  testText := 'b'+UTF8_ARABIC_LAM+UTF8_ARABIC_ALEPH+'da'+UnicodeCharToUTF8($302)+'c';
  dx[0] := 20;
  dx[1] := 20;
  dx[2] := 20;
  dx[3] := 20;
  dx[4] := 20;
  dx[5] := 20;
  Canvas.Font.Color := clBlack;
  Canvas.Brush.Color := clWhite;
  Canvas.TextOut(0,0, 'init font');
  ExtTextOut(Canvas.Handle, 10, 10, ETO_OPAQUE or ETO_PDY, @r, @testText[1], length(testText), @dx[0]);
end;  
```

<img width="322" alt="Capture d’écran 2020-09-23 à 15 17 09" src="https://user-images.githubusercontent.com/9092455/94017574-e3224700-fdaf-11ea-88c9-3ec5b8a0734e.png">

What do you get with this example?

**Comment by Alexey-T** [comment]
> "ba^c" would go with an array (20, 0, 20, 20)

with (20, 20, 0, 20). Seems. AFAIR. CudaText engine does it so.

**Comment by Alexey-T** [comment]
Will check example on win32 later

**Comment by circular17** [comment]
related to https://github.com/bgrabitmap/lazpaint/issues/119

**Comment by circular17** [comment]
I've got my hand on a Windows machine. Here is what I get:
![image](https://github.com/bgrabitmap/bgrabitmap/assets/9092455/8100b61f-c92c-4a66-a392-a82e7afc6fc4)

So, each unicode character is to be represented in the array, whether or not they combine to form a glyph.

Other info, the offset is not the letter spacing inbetween letters, but the offset between the origin of each letter.

Finally, if the glyphs are connected, the link is stretched as we can see between lam and aleph arabic letters.

**Comment by Alexey-T** [comment]
>each unicode character is to be represented in the array, whether or not they combine to form a glyph.

I expected this, as I wrote before: each WideChar has its own offset in Dx array. Even if 2 widechars form a signle glyph.

**Comment by circular17** [comment]
Ok. I've implemented it on dev. Here is how it looks:
![image](https://github.com/bgrabitmap/bgrabitmap/assets/9092455/82adc980-9b0d-43b2-b41b-0a4120bd112e)

With this code:
```pascal
procedure TForm1.FormPaint(Sender: TObject);
var
  dxy: array of TPointF;
  testText: string;
  bmp: TBGRABitmap;
begin
  testText := 'b'+UTF8_ARABIC_LAM+UTF8_ARABIC_ALEPH+'da'+UnicodeCharToUTF8($302)+'c';
  setlength(dxy, integer(UTF8Length(testText)));
  dxy[0] := PointF(20, 0);
  dxy[1] := PointF(20, 0);
  dxy[2] := PointF(20, 0);
  dxy[3] := PointF(20, 0);
  dxy[4] := PointF(20, 0);
  dxy[5] := PointF(20, 0);

  bmp := TBGRABitmap.Create(ClientWidth, 60, BGRAWhite);
  bmp.FontFullHeight := 30;
  bmp.TextOutOffset(10, 10, testText, BGRABlack, dxy);
  bmp.Draw(Canvas, 0, 0);
  bmp.Free;
end;
```

**Comment by circular17** [comment]
Can you try if and see if the output is ok for you?

Thank you very much for your patience.

**Comment by circular17** [comment]
I'm going to publish it with the next release. So if you have another feedback, you have still a few hours to do so.
