### ISSUE TITLE
Big exe footprint 1.5M

### ISSUE THREAD

**Issue by Alexey-T** [bgrabitmap/bgrabitmap#127]
CudaText Linux x64 build has +1.5 Mb if I use the lib.
What I use: TBGRABitmap, TBGRAPixel.From*, FillRect, SetPixel, Draw.
I dont use TextOut*.

can I make smaller footprint?

**Comment by circular17** [comment]
That's a good question. Some time ago, I tried to reduce the size to something like 500 kb. I am not sure what takes space, what could be removed. Maybe removing text functions could reduce the size.

**Comment by Alexey-T** [comment]
Removing the TextOut and all font related code.

**Comment by circular17** [comment]
Ok

**Comment by lainz** [comment]
In my opinion is not that much space. Say if you want to distribute that it downloads in seconds.
A picture in my phone has more space than this library.

**Comment by circular17** [comment]
Related to https://github.com/bgrabitmap/bgrabitmap/issues/159

**Comment by circular17** [comment]
Forum discussion: https://forum.lazarus.freepascal.org/index.php/topic,66508.msg509810.html#msg509810

Proposal:

- either we provide packages with BGRABITMAP_CORE directive, and then we can leave all properties as they are. This required additional maintenance for theses packages.

```pascal
uses BGRABitmap, BGRABitmapTypes, BGRACanvas{required at runtime}, SysUtils;
 
var bmp: TBGRABitmap;
begin
  bmp := TBGRABitmap.Create(400, 400, CSSSilver);
  with bmp.CanvasBGRA do
  begin
    canvas.Brush.BGRAColor := CSSGreen;
    canvas.FillRect(100, 100, 300, 300);
  end;
  bmp.SaveToFile(ExtractFilePath(paramStr(0))+'square.png');
  bmp.Free;
end.
```

- either we don't provide the packages and let people tweak the package, but then properties would be hidden and code would be a bit different. This requires less maintenance but code may not be straightforward.
```pascal
uses BGRABitmap, BGRABitmapTypes, BGRACanvas, SysUtils;
 
var bmp: TBGRABitmap;
  canvas: TBGRACanvas;
 
begin
  bmp := TBGRABitmap.Create(400, 400, CSSSilver);
  canvas := TBGRACanvas.Create(bmp); {explicit use of BGRACanvas unit}
  canvas.Brush.BGRAColor := CSSGreen;
  canvas.FillRect(100, 100, 300, 300);
  canvas.Free;
  bmp.SaveToFile(ExtractFilePath(paramStr(0))+'square.png');
  bmp.Free;
end.
```

**Comment by circular17** [comment]
I've been able to limit the colorspaces imported in the core version, or if `BGRABITMAP_NO_EXTENDED_COLORSPACE` directive is defined.

With core version, the size of BGRABitmap+BGRABitmapTypes now is 916 KB on Windows and 2113 Ko on MacOS.

I probably won't remove more from the core version. The code is in the [dev-core](https://github.com/bgrabitmap/bgrabitmap/tree/dev-core) branch and will remain there for testing for now.

**Comment by circular17** [comment]
Merged with dev
