### ISSUE TITLE
RoundRectAntialias pixel perfect borders

### ISSUE THREAD

**Issue by lainz** [bgrabitmap/bgrabitmap#129]
Hi. I noticed that by default the border is centered around the rect passed to draw the rounded rectangle. 

That causes some blur when drawing the pixels, the most left and most right pixels are blurred.

This happens for example in bcbutton when using an even border width, say 2, 4, 6 and so on.

Can you add an option to draw it inner or outer the rectangle? So it can be always pixel perfect.

It can be rrMiddle (the actual mode), rrInner, rrOuter.

**Comment by lainz** [comment]
I mean inside the rectangle or outside the rectangle.

**Comment by circular17** [comment]
I understand. Well there are various ways to approach the problem.

For example you can also shift the coordinates by 0.5 to align to pixels.

I prefer to leave that to the user to decide how to handle that.

**Comment by lainz** [comment]
Ok, I understand, so adding or removing 0.5 will do. Thanks I will try in the new repository lainzcontrols in some of these controls and if it works I will try to do it in bcbutton.

**Comment by lainz** [comment]
Thanks again, it works perfectly substracting 0.5 in both sides.
![pixelperfect](https://user-images.githubusercontent.com/4131395/94366915-7d84d200-00b1-11eb-9568-7d91808b0506.png)
