### ISSUE TITLE
Load image without or unknown extension?

### ISSUE THREAD

**Issue by fredvs** [bgrabitmap/bgrabitmap#132]
Can BGRABitmap load image and detect the fomat used (bmp, png, jpg, ...) if the filename has no or custom extension?

Can BGRABitmap give the info of what kind of image it is?

It is part related with this Lazarus post:
https://forum.lazarus.freepascal.org/index.php/topic,51665.msg379691.html#msg379691

With classic `img.LoadFromFile(aimagefile)` that is a void method (procedure, not function), I do not see how to know if the image was successfully loaded.
(but maybe then `img = nil`)

Thanks.

**Comment by circular17** [comment]
You can detect the format using DetectFileFormat functions of BGRABitmapTypes unit.

```
  {** Detect the file format of a given file }
  function DetectFileFormat(AFilenameUTF8: string): TBGRAImageFormat;
  {** Detect the file format of a given stream. ''ASuggestedExtensionUTF8'' can
      be provided to guess the format }
  function DetectFileFormat(AStream: TStream; ASuggestedExtensionUTF8: string = ''): TBGRAImageFormat;
  {** Returns the file format that is most likely to be stored in the
      given filename (according to its extension) }
  function SuggestImageFormat(AFilenameOrExtensionUTF8: string): TBGRAImageFormat;
  {** Returns a likely image extension for the format }
  function SuggestImageExtension(AFormat: TBGRAImageFormat): string;
  {** Create an image reader for the given format }
  function CreateBGRAImageReader(AFormat: TBGRAImageFormat): TFPCustomImageReader;
  {** Create an image writer for the given format. ''AHasTransparentPixels''
      specifies if alpha channel must be supported }
  function CreateBGRAImageWriter(AFormat: TBGRAImageFormat; AHasTransparentPixels: boolean): TFPCustomImageWriter; 

```
If you do a LoadFromFile, if the format was not recognized, you will get an exception.

**Comment by fredvs** [comment]
OK, many thanks.
https://forum.lazarus.freepascal.org/index.php/topic,51665.msg379756.html#msg379756
