### ISSUE TITLE
Error: Ordinal expression expected

### ISSUE THREAD

**Issue by fredvs** [bgrabitmap/bgrabitmap#134]
Hello.

While compiling last commit of dev branch, with fpc 3.2.0, and fpc 3.3.1 on Linux 64 bit, I get that error:

> bgradefaultbitmap.pas(2062,49)  Error: Ordinal expression expected:

It points to '**pssolid**' on this line:

  `if (aoPie in AOptions) or not (PenStyle in [psSolid, psClear]) then`
 
in procedure TBGRADefaultBitmap.InternalArc(...)

**Comment by fredvs** [comment]
This compile but maybe it is not what you want:

`if (aoPie in AOptions) or ((PenStyle <> psSolid) and (PenStyle <> psClear)) then`

**Comment by circular17** [comment]
What is the definition of psSolid?

**Comment by fredvs** [comment]
In **bgrafpcanvas.inc**:

```
const
  {** Pen is continuous }
  psSolid = FPCanvas.psSolid;
```

And in **fpcanvas.pp**

 `TFPPenStyle = (psSolid, psDash, psDot, psDashDot, psDashDotDot, psinsideFrame, psPattern,psClear);
`

**Comment by circular17** [comment]
Well then it is an ordinal expression so I would say it is a bug in the compiler.

**Comment by circular17** [comment]
I am surprised though because I use FPC 3.2.0 and don't have this problem.

**Comment by fredvs** [comment]
On what OS?

I did try with official fpc 3.0.4, fpc 3.2.0 and fpc 3.3.1.

Could be the mode used the cause of the problem?

I use this fpc parameter:

`-Mobjfpc -Sh -Fcutf8 `

**Comment by fredvs** [comment]
> I am surprised though because I use FPC 3.2.0 and don't have this problem.

What OS?

I did try with fpc 3.2.0 for Windows and same error.

**Comment by circular17** [comment]
I use Lazarus 2.0.10 with FPC 3.2.0 on MacOS and Windows and don't get this error.

Could be related to a compiler switch, sure. I don't know.

**Comment by fredvs** [comment]
Very strange.

I get this compiling StrumPract.

By the way, is it a crime to use this?:

`if (aoPie in AOptions) or ((PenStyle <> psSolid) and (PenStyle <> psClear)) then`

instead of original:

`if (aoPie in AOptions) or not (PenStyle in [psSolid, psClear]) then`

(because the first one compiles ok)

**Comment by circular17** [comment]
That's perfectly legal :D

**Comment by fredvs** [comment]
Ha, ok, and what do you think to change your code to become legal?

**Comment by fredvs** [comment]
But I agree with your future answer, we both would be more happy if we understand why it does not compile.

**Comment by circular17** [comment]
Well I did not say the current code was not legal.

Is it the only thing that does not compile for you?

**Comment by fredvs** [comment]
> Is it the only thing that does not compile for you?

Yes and with the fix it compiles-runs perfectly.

**Comment by fredvs** [comment]
> Well I did not say the current code was not legal.

No, not you, my compilers say it!

**Comment by circular17** [comment]
Well I have changed it on dev for the beautiful eyes of your compiler.

**Comment by fredvs** [comment]
Yep, I know, they're irresistible.

Thanks!
