### ISSUE TITLE
Cannot compile BGRABitmapPack4NoGUI 11.3.1

### ISSUE THREAD

**Issue by rchastain** [bgrabitmap/bgrabitmap#137]
Hello!
I try without success to compile BGRABitmapPack4NoGUI 11.3.1. It's on Linux with Lazarus 2.0.8.

```
bgratext.pas(207,18) Error: identifier idents no member "Brush"
bgratext.pas(208,18) Error: identifier idents no member "TextOut"
bgratext.pas(213,18) Error: identifier idents no member "Font"
bgratext.pas(220,18) Error: identifier idents no member "Brush"
bgratext.pas(224,18) Error: identifier idents no member "TextRect"
bgratext.pas(232,28) Error: identifier idents no member "TextExtent"
bgratext.pas(237,18) Error: identifier idents no member "Font"
bgratext.pas(246,28) Error: identifier idents no member "TextFitInfo"
```

I have the impression that we already talked about this, but I can't remember where. So excuse me (Johann) if you already have given to me the solution.

Regards.

Roland

**Comment by circular17** [comment]
Thanks for reporting it.

I think I made a mistake when adding support for MSEgui.

Hmmm, I will try to fix it.

**Comment by mr-highball** [comment]
believe this is also related to #138

**Comment by circular17** [comment]
fixed compilation for fpGui and noGui on dev branch
