### ISSUE TITLE
bgrabitmap compilation issues trunk fpc

### ISSUE THREAD

**Issue by mr-highball** [bgrabitmap/bgrabitmap#138]
hello, attempting to compile with trunk after cloning bgrabitmap as a submodule to my project.
I've added LazUtils as a project dependencies but when compiling I'm receiving the following issues
the first here can be solved if I remove the pointer() casts, but then results in the next set of errors
![bgra_error_1](https://user-images.githubusercontent.com/35942565/112687705-3dc75900-8e4e-11eb-9396-ca871282125c.png)

this is complaining about member properties missing from classes, and I didn't try getting around these to know if there were more issues later
![bgra_error_2](https://user-images.githubusercontent.com/35942565/112687711-4029b300-8e4e-11eb-8c18-0f97dcb30ccf.png)

**specs**
win32 OS
![image](https://user-images.githubusercontent.com/35942565/112687868-7bc47d00-8e4e-11eb-8d82-b95c163eb532.png)
![image](https://user-images.githubusercontent.com/35942565/112687910-854de500-8e4e-11eb-8eec-26ba399e4c3d.png)

any help would be appreciated,
-Highball

**Comment by circular17** [comment]
Hello. Sorry for the late answer. I don't get the problem with the release candidate of Lazarus. Maybe the problem has been fixed in FPC?
