### ISSUE TITLE
Dependencies to Lazarus

### ISSUE THREAD

**Issue by fredvs** [bgrabitmap/bgrabitmap#139]
Hello.

When compiling a console or msegui application, bgrabitmap needs files from /lazarus/components/lazutils/.

Could it be possible to consider to add in bgrabitmap directory the files needed to not oblige people to install all 
Lazarus ?

In attachment the files needed.

[lazdep.zip](https://github.com/bgrabitmap/bgrabitmap/files/6217866/lazdep.zip)

**Comment by circular17** [comment]
That's a good point

**Comment by circular17** [comment]
Related to https://github.com/bgrabitmap/bgrabitmap/issues/168

Now there is only a dependency to freetypelaz and FCL.

Actually you don't need to download all Lazarus. You can just get the following directory:
https://gitlab.com/freepascal.org/lazarus/lazarus/-/tree/main/components/freetype

**Comment by rchastain** [comment]
> Actually you don't need to download all Lazarus. You can just get the following directory: https://gitlab.com/freepascal.org/lazarus/lazarus/-/tree/main/components/freetype

I believe you also need components/lazutils, otherwise you get this error:

```
Compiling /home/roland/Documents/pascal/sources/bgrabitmap-11.5.4/bgrabitmap/bgrafreetype.pas
Compiling /home/roland/lazarus-trunk-2023-04-19/lazarus/components/freetype/easylazfreetype.pas
easylazfreetype.pas(22,31) Fatal: Can't find unit Laz_AVL_Tree used by EasyLazFreeType
```

**Comment by circular17** [comment]
LazUtils is still needed for FreeType implementation.

**Comment by fredvs** [comment]
MSEgui has his own font rendering, including unicode and freefonts.

Maybe use this instead of font rendering from Lazarus?
I will check in BGRAUTF8  maybe it could be done easy when msegui was assigned...

**Comment by circular17** [comment]
Well yes in fact in MSEgui you may render with the system using what's provided my MSEgui. So maybe you don't need FreeType at all.

**Comment by fredvs** [comment]
In what case is lazutf8 used?

In the msegui demo that you provided in BGABitmap, it uses fonts and the rendering is perfect, even for Chineese chars.

Is lazutf8 needed there?

**Comment by circular17** [comment]
I suppose it is not needed as it was necessary for FreeType which is not used anymore

**Comment by fredvs** [comment]
Tested msegui /test/fractal_tree from last BGRABitmap release.
Without any lazut8.pas added nor path to directory to lazutils.

Perfect, compiles without cry and nice font-rendering.

![testbgramsegui](https://github.com/bgrabitmap/bgrabitmap/assets/3421249/86cae2aa-1e86-4525-9a6a-d9d70724563f)

Also try to compile _StrumPract_, deleting all _lazutf8_ dependencies.
The same, compiles without tears, and nice rendering.

So good to feel free! ;-)

Well done and many thanks.

**Comment by fredvs** [comment]
Hello.

Very little detail.

When using the _fractal_tree.prj_ project file given in:
https://github.com/bgrabitmap/bgrabitmap/tree/master/test/test4ideu/fractal_tree

there could be problem for user at compilation:
https://github.com/mse-org/mseide-msegui/discussions/55#discussioncomment-5955926

This because when using some _{$ ifdef ...}_ fpc ignore it without using the -B (rebuild all) parameter.

In attachment, the fractal_tree.prj file with -B option added.
Also the color of warning and error messages were inversed, it is fixed in the attachment.

It would be great if you could replace the fractal_tree.prj so people will be able to compile out-of-the-box.

Thanks.
 
[fractal_tree.prj.zip](https://github.com/bgrabitmap/bgrabitmap/files/12311901/fractal_tree.prj.zip)

**Comment by circular17** [comment]
Ok I've applied the change on dev branch

**Comment by fredvs** [comment]
Many thanks!

**Comment by circular17** [comment]
Thank you too!
