### ISSUE TITLE
possible bug in TSVGContent.GetElement()

### ISSUE THREAD

**Issue by jk987** [bgrabitmap/bgrabitmap#140]
Hello,
I'm trying to find object by ID in SVG file.
On internet I've found following code which seems to be OK:
```
function FindElement(aSVGContent:TSVGContent; Const aName: String): TSVGElement;
var
  i: Integer = 0;
  aItem: TSVGElement;
begin
  Result := nil;
  for i := 0 to aSVGContent.ElementCount - 1 do begin
    aItem := aSVGContent.Element[i];
    if aItem = nil then continue;
    if aItem is TSVGGroup then aItem := FindElement(TSVGGroup(aItem).Content, aName);
    if SameText(aName, aItem.ID) then begin
      Result := aItem;
      Break;
    end;
  end;
end;
```

I'm calling it by:
```
... FindElement(svg.Content, 'rect3792');
```

The problem seems to be in function TSVGContent.GetElement(AIndex: integer): TSVGElement.
Sometimes the Item in FElements.Items[] is not TSVGElement.
I had to change it to:
```
function TSVGContent.GetElement(AIndex: integer): TSVGElement;
var o: TObject;
begin
  o := TObject(FElements.Items[AIndex]);
  if o is TSVGElement then
    result := o as TSVGElement
  else
    result := nil;
end;
```
Perhaps the problem is more deeper but this fix works for me.

**Comment by circular17** [comment]
Ok I take a note of that

**Comment by jk987** [comment]
I will write down my thoughts not to forget them.
I put some OutputDebugString() inside and it looks like every even element in FElement.Items[] is TDOMText and every odd is TSVGElement.

And I found property TSVGContent.IsSVGElement[], so instead of modifying TSVGContent.GetElement() I can just rewrite my function FindElement() the following way:
```
function FindElement(aSVGContent: TSVGContent; Const aName: String): TSVGElement;
var
  i: Integer = 0;
  aItem: TSVGElement;
begin
  Result := nil;
  for i := 0 to aSVGContent.ElementCount - 1 do begin
    if not aSVGContent.IsSVGElement[i] then Continue;
    aItem := aSVGContent.Element[i];
    if aItem = nil then Continue;
    if aItem is TSVGGroup then aItem := FindElement(TSVGGroup(aItem).Content, aName);
    if SameText(aName, aItem.ID) then begin
      Result := aItem;
      Break;
    end;
  end;
end;
```
Now it works ok, I'm bit smarter now and I apologize myself for bothering you.

**Comment by circular17** [comment]
Ah ok, indeed, you can solve the problem by checking first it it is an SVG element. You can as well remove:
`if aItem = nil then Continue;`

**Comment by jk987** [comment]
That line was there temporarily for debugging and now it should be one line later.
