### ISSUE TITLE
Warnings and Hints.

### ISSUE THREAD

**Issue by fredvs** [bgrabitmap/bgrabitmap#142]
Hello.

Compiling a application that uses BGRABitmap generates lot of hints and 58 warnings.
There are also some " Local variable not used".

Lot of the hints are about "Marked as inline is not inlined".
For the warnings, most of are "Warning: unreachable code".

Sometimes directive _{%H-}_ is used (to disable warning) but, sadly, this directive is working only with the Lazarus IDE and has no effect if the app is compiled via console.
In that case, imho, better to use:

  ```
  {$push}
     {$hints off}{$warnings off}
   ... // code to disable warning.
     {$pop}
```

I can try to fix some warnings but for all the "Marked as inline is not inlined" and  "Warning: unreachable code" I am not sure what to do.

Fre;D

**Comment by fredvs** [comment]
Re-hello.

>  Lot of the hints are about "Marked as inline is not inlined".

Maybe this directive could be added at begin of the units that produce this warning:
`{$warn 6058 off}`

> For the warnings, most of are "Warning: unreachable code".

And this directive for the units with that warning:
`{$warn 6018 off}`

Tested and compiler is happy now.

**Comment by fredvs** [comment]
Re-re hello.

Finally I think it is not a good idea to disable warnings (if it cannot fixed).
So sorry for the noise.

Fre;D

**Comment by circular17** [comment]
No problem

**Comment by fredvs** [comment]
Hello.

This is not important but note that using this (like in _blurbox.inc_):
`{%H-}a2: UInt32or64;`

generates, if not compiled via Lazarus, that hint:

> blurbox.inc(33,10) Note: (5025) Local variable "a2" not used

If the goal is to hide the message, better to use this:
{`$push}{$hints off}{$warnings off}a2: UInt32or64;{$pop}`

**Comment by circular17** [comment]
ok yeah I was wondering how to make this work

**Comment by fredvs** [comment]
If you compile with parameter **-vewinhq** the number of the message will appear into parentheses.

`blurbox.inc(33,10) Note: (5025) Local variable "a2" not used`

If you have checked all the notes and dont want all those  `"Local variable " " not used`,
just add that directive at begin of the unit, using the number of the message:

`{$warn 5025 off}`

**Comment by circular17** [comment]
Yeah that would be a good idea. I can add this in bgrabitmap.inc for example

**Comment by fredvs** [comment]
Imho, all those warnings and hints are good for debugging but after, when all is checked-fixed, they only scare people, are no needed and better hide it.
