### ISSUE TITLE
BGRABitmap fpc 2.4.6 compatible ?

### ISSUE THREAD

**Issue by fredvs** [bgrabitmap/bgrabitmap#144]
Hello.

I did try to compile BGRABitmap with fpc 2.6.4. (the best fpc release).

But last version of BGRABitmap uses new methods of fpc 3.x.x. like StartsWith in bgrautf8.pas.
This come from Tstringhelper that is not disponible in fpc 2.6.4.

Example in bgrautf8.pas, line 1446:

`if (currentChar.StartsWith(UTF8_ARABIC_ALEPH) or ...`

What do you think to use instead StartsWith something like this:

`if (Pos(UTF8_ARABIC_ALEPH,currentChar) = 1) or ... `

and this for all things that impeach the compilation with fpc 2.4.6 ?

This could be used too:

` {$if fpc_fullversion < 030000}`

Fre;D

**Comment by fredvs** [comment]
Re hello.

The same for RawByteString that does not exist in 2.4.6

Here description from fpc-wiki

<h1>RawByteString</h1>
<p>Single-byte character string without specified codepage</p>
<h2>Declaration</h2>
<p>Source position: systemh.inc line 467</p>


type RawByteString = ansistring;
--



<h2>Description</h2>
<p><var>RawByteString</var> is a single-byte character string which does not have any codepage associated with it. </p>
<p>This means that assigning a single-byte character string to this kind of string will not change the codepage of the string.  </p>
<p>Inversely, when assigning a <var>RawByteString</var> to a single-byte
 string, the codepage of the destination is simply set to the codepage  
of the rawbytestring: no codepage conversion happens, the reference 
count is simply increased. </p>
_____________________

So maybe use something like this in code:

` {$if fpc_fullversion < 030000} AnsiString {$else} RawByteString {$endif}`

**Comment by fredvs** [comment]
Hum, this one seems more tricky to make fpc 2.6.4 compatible:

In generatedcolorspace.inc :

`TColorHelper = type helper for TColor`

---->

`Indentifier 'Helper' not found.`

**Comment by fredvs** [comment]
Ooops, lot of things to change to be fpc 2.6.4.

Better forget it.

Sorry for the noise.

Fre;D

**Comment by circular17** [comment]
Hmmm that was ambitious.

I guess it is ok if we need a recent version of fpc.

**Comment by fredvs** [comment]
Hello Circular.

This because in Lazarus forum there are some people complaining about fpc > 2.6.4 and I wanted to check if BGRABItmap is still compatible with fpc 2.6.4.

**Comment by circular17** [comment]
I see. Well no, since it uses generics, it cannot be compiled for older versions.

**Comment by fredvs** [comment]
Ha, OK.

Do you know what was the last BGRABitmap release still compatible with fpc 2.6.4?

Thanks.

**Comment by circular17** [comment]
Generics were introduced in version 10, so maybe version 9.9.4

**Comment by fredvs** [comment]
Ha ok.

Strange that it does not compile with fpc 2.6.4. because in FPC  wiki-generics they say:

> fpc has had official support for generics in {$mode ObjFPC} since version 2.2. and in {$mode Delphi} since version 2.6.0.

**Comment by fredvs** [comment]
Re-hello.

Hum, a few line further it is written:

> The rtl-generics package is a larger, somewhat more featureful collection of generic containers written in {$mode Delphi} that tries to be compatible with the Delphi generics library. This package is provided as standard in FPC 3.1.1.+ but there is a version for FPC 3.0.4. available.

So maybe BGRABitmap uses rtl-generics and this one only avalaible for fpc >= 3.0.4.

**Comment by fredvs** [comment]
The issue is closed so just my 0.00001 €.

About generic.
...
Hum, how to begin...
...
Well, I have to confess that I am not fan.

And mainly for libraries.
Example from https://blogs.embarcadero.com/delphi-rtl-generic-vs-traditional-collections/

> Any Reason not to Use Generic Collections?
> 
> There are basically two reasons for not using the new collections. One is that if you have existing working code, you might not want to change it. Even more if the code is in a library (like VCL) changing it could cause incompatibility in code that uses the library.
> 
> The other reason is that generics in Delphi cause a significant code bloat, because for any data type used by the collection the class methods are replicated, even if almost identical. In very large applications, this has a negative effect on compile and link time and on executable side.

But also incompatibility with fpc 2.6.4. (that is the last that dont crash with -O3) and other.

Are you using a lot of generic?

Would it be envisage-able to think about convert all the _Generic Collection Classes_ that BGRABitmap use into _Classic Container Classes_  ?

Fre;D

**Comment by circular17** [comment]
Not really, I don't have much time to do so.

**Comment by fredvs** [comment]
OK, no problemo.
