### ISSUE TITLE
Can't compile bgrabitmappack4nogui.lpk from the Lazarus online package manager

### ISSUE THREAD

**Issue by MaartenJB** [bgrabitmap/bgrabitmap#148]
Hi,

I cant compile "bgrabitmappack4nogui.lpk" using the latest version of Lazarus and Bgrabitmap installed via the online package manager.

These are the error messages:
![afbeelding](https://user-images.githubusercontent.com/16285840/132464323-f2b98e00-e569-4c4d-946c-633878fcb872.png)

Lazarus 2.0.12
FPC 3.2.0

**Comment by MaartenJB** [comment]
Latest version of Bgrabitmap via github does compile. The version from the online package manager is probably outdated.

**Comment by circular17** [comment]
Fixed in version 11.4
https://forum.lazarus.freepascal.org/index.php/topic,24239.msg414525.html#msg414525
