### ISSUE TITLE
Converting TBitmap to TBGRABitmap swaps the background for transparency

### ISSUE THREAD

**Issue by salvadorbs** [bgrabitmap/bgrabitmap#150]
Hi everyone, lately I have noticed that if I try to convert a TBitmap to a TBGRABitmap, a different transparency color from the original is set.

![image](https://user-images.githubusercontent.com/3731721/140239506-273cd55e-d9b5-45bb-ac0e-7b3725abbd12.png)

Is this intentional or is it a bug? I am attaching an example project and I'm using bgrabitmap v11.4. [BGRABitmapVsBitmap.zip](https://github.com/bgrabitmap/bgrabitmap/files/7471557/BGRABitmapVsBitmap.zip)

Unfortunately I am forced to use the TBitmap format and not the TBGRABitmap directly, as I have to retrieve the image from a TImageList. Subsequently the TBGRABitmap will be added (together with others) in a TBGRAIconCursor multifile.

**Comment by circular17** [comment]
It was based on Delphi compatibility but the result is a bit random with Lazarus.

I have fixed that on the dev branch.

In the meantime, you can avoid this by specifying False for AUseTransparentColor parameter (second parameter of Create).

The Delphi behavior can still be achieved by specifying AUseTransparentColor = True.

Regards

**Comment by salvadorbs** [comment]
Tested commit 75d1ad4b25c38719e8fcd539f3b485b7a924b917 and it works. Thank you very much! I will close this issue.
