### ISSUE TITLE
TColor is changed in Lazarus trunk- your code don't compile now

### ISSUE THREAD

**Issue by Alexey-T** [bgrabitmap/bgrabitmap#153]
```

class function TColorColorspace.GetChannel(AColor: Pointer; AIndex: integer): single;
begin
  case AIndex of
  0: result := TColor(AColor^).red;
  1: result := TColor(AColor^).green;
  2: result := TColor(AColor^).blue;
  else raise ERangeError.Create('Index out of bounds');
  end;
end;

class procedure TColorColorspace.SetChannel(AColor: Pointer; AIndex: integer; AValue: single);
begin
  case AIndex of
  0: TColor(AColor^).red := Round(Clamp(AValue,0,255));
  1: TColor(AColor^).green := Round(Clamp(AValue,0,255));
  2: TColor(AColor^).blue := Round(Clamp(AValue,0,255));
  else raise ERangeError.Create('Index out of bounds');
  end;
end;
       
```
it cannot find members red/green. 
because TColor is changed in Laz now it is

- graphics unit:   TColor = TGraphicsColor;
- which uses: 
```
  TGraphicsColor = {$ifdef UseSystemUITypes}System.UITypes.TColor{$else}-$7FFFFFFF-1..$7FFFFFFF{$endif};
```

**Comment by Alexey-T** [comment]
https://gitlab.com/freepascal.org/lazarus/lazarus/-/commit/53fe133e4349f61b6014401439d7d446d9d3a15f

**Comment by fredvs** [comment]
Thanks to catch it Alexey!

Tested BGRABitmap + MSEgui with last trunk fpc 3.3.1 of today but here, all seems OK, no error at compilation.

![bgra_msegui_fpc331](https://user-images.githubusercontent.com/3421249/142445634-570bff6b-baba-4a8f-a10c-3deda590cdd6.png)

So it seems to affect LCL only.

Fred

**Comment by Alexey-T** [comment]
Again, this Laz commit broke it
https://gitlab.com/freepascal.org/lazarus/lazarus/-/commit/53fe133e4349f61b6014401439d7d446d9d3a15f

**Comment by circular17** [comment]
I don't understand why it doesn't work anymore. Any idea to fix it?

**Comment by Alexey-T** [comment]
0: result := TColor(AColor^).red;
  1: result := TColor(AColor^).green;
  2: result := TColor(AColor^).blue;

This uses some 'type helper' for TColor, right? so you need to find that helper.

**Comment by circular17** [comment]
The helper is in BGRABitmap, in the same unit, and is called TColorHelper. So it is here. That's why I wonder this would not work.

**Comment by Alexey-T** [comment]
maybe that is because you add TColor as alias

type
  PColor = Graphics.PColor;
  TColor = Graphics.TColor;  

what if you don't add the alias?

**Comment by circular17** [comment]
This alias is necessary because TColor in BGRABitmap might refer to something else if not with the LCL. I don't see how this would change something.

Am not working with trunk so I can't say. Am not sure that the problem comes from the alias. Maybe that's some compiler thing.

**Comment by circular17** [comment]
I've fixed for now by avoiding using the properties.
