### ISSUE TITLE
Error installing in ubuntu+lazarus v.2.0.12

### ISSUE THREAD

**Issue by wilco2009** [bgrabitmap/bgrabitmap#155]
After installing BGRABitmap in Ubuntu I get an linking error recompiling the IDE.

You can find bellow the content of the output window:

Build IDE: Exit code 2, Errors: 1, Hints: 2
lazarus.pp(154,7) Note: Call to subroutine "function GetDebugLogger:TLazLogger;" marked as inline is not inlined
lazarus.pp(162,3) Note: Call to subroutine "function GetDebugLogger:TLazLogger;" marked as inline is not inlined
lazarus.pp(166,1) Error: Error while linking

**Comment by circular17** [comment]
The actual linking error is not displayed by default. Can you get all messages? You can find them by right-clicking the message list and in menu Copy.

**Comment by fredvs** [comment]
Hello.

Can you test also to re-compile Lazarus without BGRABitmap package ?
Is the compilation OK ?

If no, I suspect a Lazarus problem.
What source of Lazarus are you using (trunk, release, from Ubuntu repository) ?

**Comment by circular17** [comment]
I will close the issue as there is no reply for some time. Though feel free to reopen the issue if needed.
