### ISSUE TITLE
Support AVIF picture format, please

### ISSUE THREAD

**Issue by Alexey-T** [bgrabitmap/bgrabitmap#158]
It's rather common in 2021 year.

Better do it with IFDEF, so usual code won't be bloated if disabled.

**Comment by circular17** [comment]
Merged into dev with pullrequest https://github.com/bgrabitmap/bgrabitmap/pull/152

**Comment by circular17** [comment]
Seems to work fine on MacOS (with libavif installed with Homebrew)
