### ISSUE TITLE
Loading of these TIFF files fails

### ISSUE THREAD

**Issue by Alexey-T** [bgrabitmap/bgrabitmap#160]
https://filesamples.com/formats/tiff

I tried with the first 2 sizes from there.
sample_640×426.tiff,  sample_1280×853.tiff

**Comment by circular17** [comment]
Works for me, tried on MacOS.

**Comment by Alexey-T** [comment]
I tried it on Ubuntu 20. Is it working too?

**Comment by circular17** [comment]
I don't have Ubuntu installed. I tried on Windows too, and works too:
![image](https://user-images.githubusercontent.com/9092455/170864426-29330b1d-37a8-451f-85ac-afbc17246af3.png)

Though I am using dev version. Maybe something has been fixed since then?
