### ISSUE TITLE
bgrabitmappack4nogui.lpk needs Required Package "freetypelaz" to be included

### ISSUE THREAD

**Issue by MaartenJB** [bgrabitmap/bgrabitmap#162]
Hi,

bgrabitmappack4nogui.lpk needs Required Package "freetypelaz" to be included, otherwise it wont compile.

Lazarus 2.2.0 (rev lazarus_2_2_0-29-g6d0f8f5d72) FPC 3.2.3 x86_64-linux-gtk2
Bgrabitmap v11.4 installed via online package manager 

Best regards,

Maarten

**Comment by circular17** [comment]
Done on dev
