### ISSUE TITLE
simpler init dyn arrays

### ISSUE THREAD

**Issue by Alexey-T** [bgrabitmap/bgrabitmap#163]
Assign of Nil to dyn array is the same as call SetLength(..., 0).
you have n places:
![bb](https://user-images.githubusercontent.com/4154978/150517826-82e1887c-ad2d-44ef-aba4-4a3b5a8284ce.png)

**Comment by circular17** [comment]
True. Not very important though.

**Comment by circular17** [comment]
I've applied the change. This can lead to less "uninitialized" warnings from the compiler.
