### ISSUE TITLE
SVG Memory Leak?

### ISSUE THREAD

**Issue by Intuineo** [bgrabitmap/bgrabitmap#166]
Hi,

I am using TBCSVGViewer as base component to create a SVG Button. The component calls:

```
procedure TMySVGButton.GenerateSVGImage(const aValue: String);
begin
  DiscardBitmap;
  if aValue <> ''
    then FSVG.CreateFromString(aValue) else
    begin
      if FSVGNormal.Count > 0
        then FSVG.CreateFromString(FSVGNormal.Text);
    end;
  RedrawBitmap;
end;   
```
 and it seems I have some memory leaks, here and in some other places :

```
destructor TSVGDataLink.Destroy;
var
  i: Integer;
begin
  //for i := FChildren.Count-1 downto 0 do
  //  TSVGDatalink(FChildren[i]).Parent := nil;

 //Changed to:
  for i := FChildren.Count-1 downto 0 do
    begin
    TSVGDatalink(FChildren[i]).Parent := nil;
    TSVGDatalink(FChildren[i]).Free; // changed
    end;  

  Parent := nil;
  FreeAndNil(FChildren);
  FreeAndNil(FLinkListeners);
  FreeAndNil(FElements);
  FreeAndNil(FStyles);
  inherited Destroy;
end;
```

Could you please have a look?
Thanks,
Luc

**Comment by Alexey-T** [comment]
Pls use triple backticks - in the begin and in the end of code. It's markdown feature.

**Comment by Intuineo** [comment]
Thanks Alexey, done.

**Comment by circular17** [comment]
There is a memory leak in the XML component of Lazarus/FreePascal, that's probably it. If that's what I am thinking about, it is a small leak, and I guess it doesn't grow.

**Comment by circular17** [comment]
Calling FSVG.CreateFromString will probably cause a memory leak. It is a constructor, it is supposed to be called only once when the object is instantiated. If you would like to change the content based on the string, there is AsUTF8String property for that.
