### ISSUE TITLE
BGRABitmap.TextOut and msegui ?

### ISSUE THREAD

**Issue by fredvs** [bgrabitmap/bgrabitmap#167]
Hello!

I try to write text on a msegui form using this:

```
var
  image:TBGRABitmap;
 ...
  image := TBGRABitmap.Create(ClientWidth,ClientHeight, BGRAwhite );
  image.FontHeight := 30;
  image.FontAntialias := true;
  image.FontStyle := [fsBold];
  image.TextOut(5,5,'Hello world',BGRAblack);
  image.Draw(aCanvas,0,0,True);
  image.free;
```
But I only get a white canvas.
Do I miss something ?

All other paints like GradientFill, DrawLineAntialias, etc, ... are drawing perfectly.

Thanks.

Fre;D

**Comment by circular17** [comment]
Normally using TextOu goes in BGRAText and there are compiler defines there to use the correct code.

**Comment by fredvs** [comment]
Hell Circular, I hope all ok for you.

> and there are compiler defines there to use the correct code.

Hum, ok, mais encore...?
What compiler defines are you talking about?

Do you think that with BGRAText it would be possible to render Chineese ideogram in Linux, like 是的全部 ?
We have problems to render that ideograms in msegui on Linux with the build-in msegui components (ok on Windows).

So I was thinking that maybe using BGRABitmap could help us ( and so create some BGRA-msegui components with Chineese ideogram compatibility on Linux).

Fre;D

**Comment by fredvs** [comment]
> and there are compiler defines there to use the correct code.

Ha, are you talking about _-dBGRABITMAP_USE_MSEGUI_ ?

If so, yes, of course it was set but the canvas is always only white.

**Comment by fredvs** [comment]
Hello.

I try to find where to look to have font rendering with msegui...
Is bgrafreetype.pas needed ?

Or maybe font rendering is allowed only for LCL?

Thanks.

Fre;D

**Comment by fredvs** [comment]
In BGRAText.pas, there are lot of _{$IFDEF BGRABITMAP_USE_MSEGUI}_ so it seems MSEgui compatible.

I am lost and in the dark, sure I miss something, but what ?

Fre;D

**Comment by fredvs** [comment]
Ok, ok, ok, found this:
https://github.com/bgrabitmap/bgrabitmap/issues/79#issuecomment-614699414

Circular said that:
```
//drawing some text with MSEgui canvas
  f := tfont.create;
  f.height := 20;
  bmp.canvas.drawstring(test_text, 
    makepoint((bmp.width - bmp.canvas.getstringwidth(test_text, f)) div 2, 
               bmp.height div 6), f);
  f.free;
```

And using this code using:

_Txt := 'Yeeeep' ;_ 

gives that:
![bgramsetext](https://user-images.githubusercontent.com/3421249/158038160-8d40c4db-d180-4a99-9300-e3f95a30b4a6.png)

So PERFECT, BGRAText works with MSEgui!

Now about Chineese ideograms, is there a way to render it?
For example using this:

 _Txt :=_ '是的全部' ;

gives that:
![bgramsetext](https://user-images.githubusercontent.com/3421249/158038324-992d706b-2070-4540-b3b4-303227c3be86.png)

Fre;D

**Comment by fredvs** [comment]
Yeeep, I get it for Chinese ideograms !

The trick for Linux:

1) In console look for the font installed compatible with Chinese ideograms:

`$ > fc-list :lang=zh`

2) Chosse one, I took randomily **'Noto Serif CJK TC'**

3) In code, add the font name:
  
```
  f := tfont.create;
  f.name := 'Noto Serif CJK TC';
```
 
And you will get this:
![bgramsetextchineese](https://user-images.githubusercontent.com/3421249/158040403-d1d74206-7b52-4ff4-8069-531ceafc194a.png)

WOW BGRABitmap and so sorry for the noise ( but so happy too ).

Fre;D

**Comment by circular17** [comment]
Am puzzled though that it doesn't work directly with TBGRABitmap.TextOut.

**Comment by circular17** [comment]
I think I found the problem. msegui needed the TBitmap to have a non-zero size to compute the text size. That's fixed on dev.

I've also fixed a compilation problem.

Can you try with dev branch?

I also updated the example to display some text.

**Comment by circular17** [comment]
![image](https://user-images.githubusercontent.com/9092455/172195999-fca5ef85-96e3-4ccb-b09f-d7034ec06f41.png)

I noticed that the left border is cropped. Drawing a yellow rectangle, the left side is not visible.

**Comment by fredvs** [comment]
OK, many thanks, I will try it tonight.
Write you later.

**Comment by circular17** [comment]
Ok. À plus tard.

**Comment by fredvs** [comment]
Ok, voici mes notes:

_tpaintbox1_ has strange bounds: **x = -6** and **y = 10.**
And the anchors, if you want that _tpaintbox1_ covers all the form, should be:
 **an_left = false, an_right = false, an_top = false, an_bottom = false**
I know it is a little strange but it is the "msegui" way to cover all the parent.

Rremoving the line: _bmp.Rectangle(0, 0, bmp.Width, bmp.Height, CSSYellow);_
remove the top yellow line.
By the way, what is the goal of that line?

![fractral_tree](https://user-images.githubusercontent.com/3421249/172214931-5ce8b235-3785-4262-a1e8-68c324bfcee9.png)

If you want I may do a pull-request with those change.

**Comment by circular17** [comment]
I am confused are you talking about the code for the yellow line? I've added it to check for the bounds of the picture.

But well yellow is not great here, I will put black instead, and add another one.

I've added also some gradient text for testing.

No need for the pull request. Though if you still see something in the code I would be happy to know.

**Comment by circular17** [comment]
![image](https://user-images.githubusercontent.com/9092455/172306554-4eb79862-b189-47f4-9fbd-6a723f3a4530.png)

**Comment by fredvs** [comment]
Super WOW for the gradient text!
Many thanks.

**Comment by fredvs** [comment]
FPC is rich because of you Johann.

And BGRABitmap + MSEgui gives a 100 % Pascal high quality solution for many OS/CPU.
I dont think something like this exists in other languages.

Lot of respect to you Johann.

Fre;D

**Comment by circular17** [comment]
Thanks a lot! Am really happy to contribute. I started playing with pixels on my own, alone somewhere on a computer. And now many people can enjoy it! 🐥
