### ISSUE TITLE
bug report, for package on Android

### ISSUE THREAD

**Issue by Alexey-T** [bgrabitmap/bgrabitmap#169]
https://forum.lazarus.freepascal.org/index.php/topic,58624.msg436763.html#msg436763

**Comment by circular17** [comment]
I've added a package for Android: https://github.com/bgrabitmap/bgrabitmap/commit/6d74d6905b10a47f3f8fa2a95723171710bb6785

It took me time to make up my mind, without the Android environment, and wanting an elegant solution.
