### ISSUE TITLE
TBGRABitmap’s bug in Linux: transparent color is drawn instead of clBlack

### ISSUE THREAD

**Issue by neurocluster** [bgrabitmap/bgrabitmap#170]
TBGRABitmap has a bug in Linux: when clBlack color is drawn, the transparent color is drawn instead of clBlack. This bug does not happen in Windows and macOS. This bug happens only in Linux. 
Instructions how to reproduce the bug: create TBGRABitmap and draw black line or black PNG image on TBGRABitmap.Canvas – the transparent color is drawn instead of clBlack.
Now I use the following workaround solution for this bug: I use TColor($010101) instead of TColor($000000) – the human eye does not see the difference, however TBGRABitmap draws black color as it is supposed to do. 
This bug needs to be fixed because it is very inconvenient to edit every PNG image with Photoshop and to change all pixels having TColor($000000) into TColor($010101).

```
var:
bgra_bitmap: TBGRABitmap;
png: TPortableNetworkGraphic;

begin
png := TPortableNetworkGraphic.Create;
png.LoadFromLazarusResource('IMAGE01');
bgra_bitmap := TBGRABitmap.Create(png.Width, png.Height);
bgra_bitmap.Canvas.Draw(0,0, png);
bgra_bitmap.Canvas.Pen.Color := clBlack;
bgra_bitmap.Canvas.Line(0,0, 100, 100);
```

The second problem of TBGRABitmap in Linux: when PNG image is drawn on TBGRABitmap.Canvas, the contact line between areas of different colors is very pixelated and not smooth. This problem does not happen in Windows and macOS. Problem happens only in Linux.
This problem does not happen in Linux when EllipseAntialias(...) or Arc(...) functions are used to draw ellipses/arcs. The problem happens in Linux only when drawing PNG images on TBGRABitmap.Canvas.
Sample screenshot is attached: blue hexagonal figures with black perimeter are PNG images, while black circles and brown arcs are drawn using EllipseAntialias(...) and Arc(...) functions.
![image](https://user-images.githubusercontent.com/101508556/163353917-a0a9dd50-2ce3-4090-bb9f-bbb1e9a9f732.png)

**Comment by circular17** [comment]
Yes this is a known limitation of the Canvas property. It is recommended to avoid using it. There is an alternative CanvasBGRA property that handles transparency and black colors.

If you really need to use Canvas, the use clBlackOpaque color instead of clBlack, provided in the BGRABitmapTypes unit.
