### ISSUE TITLE
BGRAGames package compiles in Windows, however fails to compile in macOS and Linux

### ISSUE THREAD

**Issue by neurocluster** [bgrabitmap/bgrabitmap#171]
BGRAGames package compiles in Windows, however fails to compile in macOS and Linux.

**Comment by lainz** [comment]
On Linux you need to install some packages first. I think libxtst-dev and libgl-dev.

On macOS there's no OpenGL AFAIK.

**Comment by lainz** [comment]
https://wiki.lazarus.freepascal.org/BGRA_Installation_on_Linux
