### ISSUE TITLE
TBGRASVG can't open a certain SVG files

### ISSUE THREAD

**Issue by afuriza** [bgrabitmap/bgrabitmap#176]
So, I wrote this code to display KDE icons:
```pascal
bsvg := TBGRASVG.Create;
bsvg.LoadFromFile(paths[i] + name +'.svg');
bmp := TBGRABitmap.Create(64, 64);
bsvg.StretchDraw(bmp.Canvas2D, taCenter, tlCenter, 0, 0,
  bmp.Width, bmp.Height);
bsvg.Free;
Result := bmp;
```
And, I got a FGL error index out of bounds:
![bg3](https://user-images.githubusercontent.com/17453269/174469027-a85d2df7-20bb-429f-8e68-32bab21c0f40.jpg)
![bg2](https://user-images.githubusercontent.com/17453269/174469109-51e547ee-c1e5-4348-829e-c64005257da1.jpg)
Some icons become black:
![bg1](https://user-images.githubusercontent.com/17453269/174469394-eda0a556-6660-4c25-afe3-cd097b27b98b.png)

Test SVGs:
![kwalletmanager](https://user-images.githubusercontent.com/17453269/174469599-92a80a82-6959-489f-a1e7-5feec672668b.svg)
![kwrite](https://user-images.githubusercontent.com/17453269/174469609-982e649f-f9ff-458e-bc0d-98a4e8d6c080.svg)

Test project:
[svgtest.zip](https://github.com/bgrabitmap/bgrabitmap/files/8934894/svgtest.zip)

**Comment by Freihut** [comment]
Mentioned this (or a very similar) issue also here and included example-svgs to trigger or not trigger this: https://github.com/bgrabitmap/bgracontrols/issues/130#issuecomment-1717680690

**Comment by circular17** [comment]
This is fixed on dev. The reason was that coordinates were not separated by spaces. I've adapted the parser to guess where the number start or end.
