### ISSUE TITLE
Wiki (FPC site): off-by-one in annotations for helper image in tutorial 13

### ISSUE THREAD

**Issue by BugsBeGone** [bgrabitmap/bgrabitmap#179]
I've actually used that tutorial many times to refresh my memory about how float coordinates work, and have only just noticed this now. I'd make the change myself, but I don't have a wiki account, and it might be easier if anyone still has the original image files.

The labels for (4,4) & (5,5) in https://wiki.freepascal.org/File:BGRATutorial13a.png should be (3,3) & (4,4) respectively.

**Comment by circular17** [comment]
True! How did I miss that? Thanks for telling me.

I've fixed it. You might need to reset cache to see the change.

Regards
