### ISSUE TITLE
Perspective warping

### ISSUE THREAD

**Issue by markthepiggy** [bgrabitmap/bgrabitmap#183]
Hi Folks,
I hope this is the right forum for this question...

I have a need to transform the perspective of an image so that it appears 'straight'. This is prior to doing measurements on it. NVidia have a function in there VPI library called "[vpiSubmitPerspectiveWarp](https://docs.nvidia.com/vpi/algo_persp_warp.html)"

It takes an input that looks like this:
![Input](https://user-images.githubusercontent.com/8985791/201759233-7cb4bdd0-637d-4797-9ad3-f0ed870373e3.png)
and produces output that looks like this:
![Ouput](https://user-images.githubusercontent.com/8985791/201759353-a28c9eb4-454b-426f-919d-0c596ea5fb73.png)

I have tried to use "TBGRABitmap.FillPolyPerspectiveMapping" which looked promising but doesn't seem to do it.

Can anyone suggest an approach that might work?

**Comment by circular17** [comment]
I suggest to look at TPerspectiveTransform and TBGRAPerspectiveScannerTransform classes of BGRATransform. Not sure what measurements you have but it provides various functions to specify the perspective transform and to invert it.
