### ISSUE TITLE
Utilize TPointF.Length

### ISSUE THREAD

**Issue by Alexey-T** [bgrabitmap/bgrabitmap#186]
```
function TPointF.Length: Single;
begin     //distance(self) ?
  result:=sqrt(sqr(x)+sqr(y));
end;
```
allows to avoid some calculating `*` (or now `**`).

**Comment by circular17** [comment]
I will try to keep it in my mind.

**Comment by LongDirtyAnimAlf** [comment]
Sidemark. Be carefull, I tried this already, but it gave overflow errors due to the use of EmptyFloat.

**Comment by circular17** [comment]
Ok so instead I optimized `VectLen` function:
```pascal
function VectLen(const v: TPointF): single;
begin
  if isEmptyPointF(v) then
    result := EmptySingle
  else
    result := sqrt(sqr(v.x) + sqr(v.y));
end; 
```

And used it to compute length instead of `sqrt(v*v)`

**Comment by Alexey-T** [comment]
No fixed.
I used CudaText plugin FindInFiles and found these

![bg](https://user-images.githubusercontent.com/4154978/209346837-aa36f866-adc6-4959-82a4-d80c60f31b57.png)

**Comment by circular17** [comment]
It is on dev branch
