### ISSUE TITLE
LCLWin64 is not considered

### ISSUE THREAD

**Issue by Alexey-T** [bgrabitmap/bgrabitmap#189]
bgrabitmap.pas
```
	  {$IFDEF LCLwin32}
		BGRAWinBitmap,
	  {$ELSE} 
```
What about LCLWin64?

**Comment by circular17** [comment]
As far as I know, Win32 is the widgetset regardless of 32-bit or 64-bit processor. What would be LCLWin64?

**Comment by Alexey-T** [comment]
It is windows 64-bit, ie LCLWin32 is not defined (as I know) when Win64 is used.

**Comment by circular17** [comment]
I am surprised by this as I have compiled programs using BGRABitmap to 64bit and did not get an error.

**Comment by Alexey-T** [comment]
seems I was not right. sorry. close this.

**Comment by circular17** [comment]
Ok. Anyway it is better to check. So thanks.

**Comment by Alexey-T** [comment]
I checked now. it's wrong info.

**Comment by fredvs** [comment]
Huh, if I may,  (but it is not important and sure there is (was) a reason):

The lines that follow OP code:

```
{$ELSE}
		{$IFDEF LCLgtk}
		BGRAGtkBitmap,
		{$ELSE}
		  {$IFDEF LCLgtk2}
		BGRAGtkBitmap,
		  {$ELSE}
```
Could not be ?:

```
{$ELSE}
		{$IF defined(LCLgtk) or defined(LCLgtk2)}
		BGRAGtkBitmap,
		{$ELSE}
```

( This to make some noise...)

Happy new all 4 all.

Fre;D

**Comment by fredvs** [comment]
About "question" label.
There is a nice (imho) new feature with GitHub: Discussion:
https://docs.github.com/en/discussions/quickstart

You may even transferred issues into discussions.

Here Discussion enabled for mseide-msegui:
![discussion](https://user-images.githubusercontent.com/3421249/209880970-0c71cd8d-882b-4d95-b69c-5b9f7657f63e.png)

The same for ideU (with issues transferred as discussions):
https://github.com/fredvs/ideU/discussions

Maybe it could be cool to have this for BGRABitmap too.

**Comment by regs01** [comment]
LCLWin32 is not referring to TargetOS, but to API that is called Win32 API. More recently Microsoft prefer to referring it as just Windows API.
https://learn.microsoft.com/en-us/windows/win32/api/

Even if you compile an app against Win64/aarch64 LCLWidgetType is still LCLWin32, as it would be using widgetset from Windows API.
