### ISSUE TITLE
Problem with a animated GIF

### ISSUE THREAD

**Issue by ClaudioYa** [bgrabitmap/bgrabitmap#192]
![a](https://user-images.githubusercontent.com/26105701/213596997-e1f09463-0f8e-403b-a14d-ec115e26ba2f.gif)

Hello,

This file can't load by animated GIF.

Regards

**Comment by circular17** [comment]
Hello!

Indeed that's a pity not to read this lovely gif.

**Comment by circular17** [comment]
I've applied a patch on dev branch to accommodate for this file. Will be in the upcoming release. Enjoy!
