### ISSUE TITLE
Cannot compile BGRABitmap and my project separately

### ISSUE THREAD

**Issue by rchastain** [bgrabitmap/bgrabitmap#193]
Hello !

I am trying to build BGRABitmap and my project separately as it is done, for example, in fpGUI projects, that is without sending to the compiler the path to library source code, but only the path to binaries.

I get this error : 

```
[roland@localhost source]$ make
Compiling Release Version
Free Pascal Compiler version 3.2.0 [2020/07/05] for x86_64
Copyright (c) 1993-2020 by Florian Klaempfl and others
Target OS: Linux for x86-64
Compiling eschecs.pas
PPU Loading ./units/lib/x86_64-linux/bgragraphics.ppu
PPU Source: bgragraphics.pas not found
PPU Source: bgrabitmap.inc not available
PPU Source: bgrafpgui_uses.inc not available
PPU Source: bgrafpgui.inc not available
PPU Source: bgrafpcanvas.inc not available
PPU Source: bgrafpgui.inc not available
PPU Source: bgrafpcanvas.inc not available
Recompiling BGRAGraphics, checksum changed for ./units/lib/x86_64-linux/fpg_base.ppu
bgragraphics.pas(66,13) Fatal: Can't find unit BGRAGraphics used by BGRABitmapTypes
Fatal: Compilation aborted
Error: /usr/bin/ppcx64 returned an error exitcode
make: *** [Makefile:12 : eschecs] Erreur 1
[roland@localhost source]$ 
```

I did read discussions about "checksum changed" issue. It would come either from circular references, or from inline functions. I tried to remove all `inline` directives from BGRABitmap. It seems that this doesn't solve the issue.

Another thing I noticed, is that when I build my project using my [old method](https://gitlab.com/rchastain/eschecs/-/blob/master/source/Makefile), FPC always recompiles _bgragradients.pas,_ I don't know why.

```
[roland@localhost source]$ make
Compiling Release Version
Free Pascal Compiler version 3.2.0 [2020/07/05] for x86_64
Copyright (c) 1993-2020 by Florian Klaempfl and others
Target OS: Linux for x86-64
Compiling eschecs.pas
Compiling ./chess/chessgame.pas
Compiling ./chess/chesstypes.pas
Compiling ./chess/chessboard.pas
Compiling ./chess/fen.pas
Compiling ./chess/chessutils.pas
Compiling ./chess/movelist.pas
Compiling ./chess/san.pas
Compiling ./chess/eco.pas
Compiling ./chess/fenfilter.pas
Compiling ./chess/pgnwrite.pas
Compiling uci.pas
Compiling bgrachessboard.pas
Compiling images.pas
Compiling ./libraries/bgrabitmap/bgrabitmap/bgragradients.pas
Compiling utils.pas
Compiling settings.pas
Compiling language.pas
Compiling ./chess/book.pas
book.pas(367,3) Note: Local variable "first_entry" is assigned but never used
book.pas(444,3) Note: Local variable "i" not used
book.pas(446,3) Note: Local variable "total_weight" not used
Compiling connect.pas
Compiling engines.pas
Compiling movestring.pas
Compiling permission.pas
Compiling sound.pas
Compiling ./libraries/uos/src/uos_flat.pas
Compiling formstyle.pas
Compiling formabout.pas
icon.pas(3,3) Note: Local variable "eschecs_icon" not used
Compiling formdebug.pas
icon.pas(3,3) Note: Local variable "eschecs_icon" not used
Compiling formpromotion.pas
Linking ../eschecs
15503 lines compiled, 3.5 sec
5 note(s) issued
[roland@localhost source]$ 
```

It is not very important. I can continue to build my project as I did until now, but I wanted to report this, in case someone would have ideas on that topic.

Regards.

Roland

**Comment by circular17** [comment]
Hi Roland,

It seems the reason for recompiling BGRAGraphics is: `checksum changed for ./units/lib/x86_64-linux/fpg_base.ppu`

So maybe it would be related to different compiler options for fpGui?

It is indeed suprising that it recompiles BGRAGradients. Is it explicitly used somewhere?

**Comment by rchastain** [comment]
Thank you for your answer.

No, unless I miss something, the options are the same.

Yes, it is explicitely used [here](https://gitlab.com/rchastain/eschecs/-/blob/master/source/images.pas), like other units from the library.

**Comment by circular17** [comment]
Hmm ok, so nothing specific about BGRAGradients.

I am a bit puzzled. I would suppose that the fpg_base unit is not the same depending on the compilation context.

**Comment by rchastain** [comment]
I will try to make a simple test project, so we can experiment.

By the way, could you remind me if there is something like `BGRABITMAP_USE_FPGUI` for a simple Pascal program? Is it `BGRABITMAP_USE_FPCANVAS`? I would like to make a test with a simple program, while we are on that topic.

**Comment by circular17** [comment]
Yes there is `BGRABITMAP_USE_FPGUI`. You can see that if you go in the Options of the package BGRABitmapPack4fpGui. In the tree, go in "Options du compilateur" and choose item "Options personnalisées". There is a text area with:
```
-dBGRABITMAP_USE_FPGUI
```

**Comment by rchastain** [comment]
My question was not very clear. It was about a simple program without GUI. But anyway you answered. I just had to take a look in the package 4nogui and I found this:

```
-dBGRABITMAP_DONT_USE_LCL
```

**Comment by rchastain** [comment]
Essai réussi également avec un programme console.

**build_lib.cfg**
```
-Mobjfpc
-Sh

-dBGRABITMAP_DONT_USE_LCL

-Fu/home/roland/fpcupdeluxe/lazarus/components/lazutils/
-Fu/home/roland/fpcupdeluxe/lazarus/components/freetype/

-FUunits
```

**build_proj.cfg**
```
-Mobjfpc
-Sh

-Fuunits
```

**Makefile**
```
project:
	fpc @build_proj.cfg test.pas
lib:
	mkdir -p units
	fpc @build_lib.cfg /home/roland/Documents/pascal/sources/bgrabitmap-11.5.3/bgrabitmap/bgrabitmap.pas
```

Voilà, je ferme la discussion.

**Comment by circular17** [comment]
Super.
