### ISSUE TITLE
Minor issue with (Internal)TextOutCurved

### ISSUE THREAD

**Issue by DomingoGP** [bgrabitmap/bgrabitmap#194]
If I want to render only the outline of a text and set the font color to transparent  (alpha=0) the function exits without rendering the text.

The line 1940 optimises aggressively without regard to the ltext outline which may not be transparent. one easy workaround is use BGRA(0,0,0,1) instead of BGRA(0,0,0,0).

` if (ATexture = nil) and (AColor.alpha = 0) then exit;`

**Comment by circular17** [comment]
Indeed.

Thinking about it, I noticed that there is not such optimization in the basic text rendering functions. So I will add them there.

I've changed the way it checks by adding a TextVisible function in the text renderer.

Does it solved the problem?

**Comment by DomingoGP** [comment]
Tested 
TextOutCurved and TextOutAngle using  TBGRAVectorizedFontRenderer and works well and solves the problem.

Also tested with **TBGRATextEffectFontRenderer** and
TextOutAngle works Well
but **TextOutCurved FAILS**

**Comment by circular17** [comment]
Indeed, I missed TBGRATextEffectFontRenderer. I've done the same for this class.

**Comment by DomingoGP** [comment]
Now works well for me.
Thank you very much.
Closing.
