### ISSUE TITLE
Font awesome are not rendered correctly  

### ISSUE THREAD

**Issue by yonist** [bgrabitmap/bgrabitmap#196]
Hi, I tried some font awesome SVG files and they are not rendered correctly in the test application.  by that that I mean the way it is rendered in Edge it looks different and correct (you will notice that circles are not really rounded, and some lines are not really aligned) for example. Is there away to control how it is being rendered?

![image](https://user-images.githubusercontent.com/499992/224055802-46bb27d0-3dcb-4b17-b047-f66ce10b1e96.png)

I'm also attaching the SVG file (it is part of their free package) 
![basketball](https://user-images.githubusercontent.com/499992/224055954-45b4fe2d-fda6-4968-b65c-9302f674b7d2.svg)

**Comment by circular17** [comment]
I think I see what you are saying. In the test SVG application, the image is rendered at a certain resolution defined by the SVG. Then it is scaled in the left part of the image. So it is expected that you see some artifacts related to this. It does not mean that it won't be rendered smoothly.

**Comment by circular17** [comment]
I think it is fine.
