### ISSUE TITLE
Class type expected, but got "untyped"

### ISSUE THREAD

**Issue by fredvs** [bgrabitmap/bgrabitmap#198]
Hello.

I try to use last commit of develop branch but there is that error at compilation, tested with fpc 3.2.2 and 3.3.1 on Linux 64 and 32 bit:

**_unibitmap.inc(2276,36) Error: (4009) class type expected, but got "untyped"_**

```
procedure TCustomUniversalBitmap.ReallocData;
begin
  ReAllocMem(FDataByte, FHeight * FRowSize);
  if (FNbPixels > 0) and (FDataByte = nil) then
    raise SysUtils.OutOfMemoryError; // here error
  InvalidateBitmap;
  FScanPtr:= nil;
end;
```

I fixed it with this:

`raise SysUtils.Exception.Create('Out Of Memory Error');`

**Comment by circular17** [comment]
The idea is to avoid allocating memory. Though maybe it is not to be used like that.

**Comment by fredvs** [comment]
Ha, ok.
But _raise OutOfMemoryError_ raise CompilationError....

;-)

**Comment by circular17** [comment]
Yes I’ve understood ☺️

**Comment by circular17** [comment]
That's fixed
