### ISSUE TITLE
Cannot find lazutf8classes

### ISSUE THREAD

**Issue by lainz** [bgrabitmap/bgrabitmap#201]
bgrautf8.pas(10,72) Error: Cannot find lazutf8classes used by BGRAUTF8 of package BGRABitmapPack.
https://forum.lazarus.freepascal.org/index.php/topic,63673.msg482696.html#msg482696

**Comment by fredvs** [comment]
Maybe reconsider this?: https://github.com/bgrabitmap/bgrabitmap/issues/139

**Comment by DomingoGP** [comment]
Hi 

With this patch the package compiles with lazarus trunk, also replaces the deprecated UTF8CharacterLength 

Regards
Domingo.

[utf8.patch](https://github.com/bgrabitmap/bgrabitmap/files/11826341/utf8.patch)

**Comment by afriess** [comment]
If the patch is ok, can the OPM please updated.

**Comment by Shebuka** [comment]
@DomingoGP can you create a PR with this patch applied?

**Comment by DomingoGP** [comment]
Created.

Circular feel free to close the pull request if you prefer to solve the issue in a different way.

**Comment by circular17** [comment]
Ok I applied your patch, thanks!

**Comment by circular17** [comment]
> If the patch is ok, can the OPM please updated.

Yes, I will wait for people to confirm it is all okay.

**Comment by circular17** [comment]
> Maybe reconsider this?: #139

LazUtils is still needed for FreeType

**Comment by circular17** [comment]
By the way, I've also done some minor adjustments to reduce the number of compilation warnings.

**Comment by afriess** [comment]
For me the patch is ok. I have inserted the changes by hand and was ok to create a fpc-fixes with Lazarus trunk.


Am 25. Juni 2023 16:52:46 MESZ schrieb circular17 ***@***.***>:

**Comment by circular17** [comment]
I've been able to compile as well with Lazarus 2.2.6 and FPC 3.2.2

**Comment by circular17** [comment]
I've added a compilation directive, but that's not great, because it relies on manually adjusting bgrabitmap.inc:
```pascal
uses
  LazVersion, BGRAClasses, SysUtils, math, BGRAUnicode
  {$IFDEF BGRABITMAP_USE_LCL},
    {$IFDEF BGRABITMAP_USE_LCL22}
      classes
    {$ELSE}
      LazUTF8Classes
    {$ENDIF}
  {$ENDIF}; 
```

I've tried using LazVersion unit, but the const does not seem to be defined in the `uses` clause.

**Comment by DomingoGP** [comment]
> I've tried using LazVersion unit, but the const does not seem to be defined in the uses clause.

Unfortunately, it seems that it is not defined within the uses.
This new patch partially reverts the first patch and  is more backwards compatible with older lazarus versions but still needs to manually modify bgrabitmap.inc  :-(

[utf8_2.patch](https://github.com/bgrabitmap/bgrabitmap/files/11860770/utf8_2.patch)

**Comment by CardanoDVPR** [comment]
I find myself in this situation and have never applied a .patch file. Can someone outline the process for getting BGRABitmap to compile and make usable within FP and Lazarus please? I apologize for being uninformed about this. Can't find this .patch process (or is this only for github use--but then I still don't know how to get BGRABitmap working for me).

**Comment by circular17** [comment]
Hello CardanoDVPR. Which version of Lazarus are you using?

**Comment by CardanoDVPR** [comment]
Lazarus version 3.99, Free Pascal version 3.3.1.

**Comment by circular17** [comment]
Ok so probably you can use _dev-bgrabitmap_ branch. Do you know how to retrieve it?

**Comment by CardanoDVPR** [comment]
Yes. I have it. But now I have a new error: unibitmap.inc(2463,5) Error: Identifier not found "ResolutionUnit"

**Comment by circular17** [comment]
Ah ok. ResolutionUnit is defined on line 529 like this:
```pascal
    {$IF FPC_FULLVERSION<30301}
    //Resolution
    property ResolutionUnit: TResolutionUnit read FResolutionUnit write SetResolutionUnit;
    property ResolutionX: Single read FResolutionX write FResolutionX;
    property ResolutionY: Single read FResolutionY write FResolutionY;
    property ResolutionWidth: Single read GetResolutionWidth;
    property ResolutionHeight: Single read GetResolutionHeight;
    {$ENDIF} 
```
So I suppose that you have trunk version of FPC, but not the latest version of it. So I suggest either to use a stable version of FPC or to update to latest trunk.

**Comment by CardanoDVPR** [comment]
The perils of trying to stay up to date. I needed the trunk for some other functionality. Ok. Thank you for your help.

**Comment by circular17** [comment]
Indeed. Well maybe the functionality you need is also in the latest update of trunk. Cheers
