### ISSUE TITLE
Reader/Writer Classes derived from fcl-image

### ISSUE THREAD

**Issue by maxm74** [bgrabitmap/bgrabitmap#210]
I noticed that all the reader/writer classes are almost identical copies of the classes in fcl-image. Why don't we work on the base classes for the changes that concern them? 
For example: 
 The last changes on BGRAWriterPNG.DoFilter should be done in the base class TFPWriterPNG.DoFilter method.
 The method should not exist in our class because it is identical to the base class.
This happens in all Reader/Writer classes.

**Comment by circular17** [comment]
The reason is that making changes in BGRABitmap directly was faster than waiting for a release of FPC. Though we could submit fixes to FPC.
