### ISSUE TITLE
Illuminant: string

### ISSUE THREAD

**Issue by Alexey-T** [bgrabitmap/bgrabitmap#211]
```
  TXYZReferenceWhite = packed record
    X, Y, Z: single;
    ObserverAngle: integer;
    Illuminant: string;
    L,M,S: single;
  end;
```

string field here. and `string` params in relatted functions. stupid guess now. if string length is limited, let's use `String[N]` to avoid mem allocs?

**Comment by circular17** [comment]
In BGRABitmap, an illuminant is not supposed to be modified or passed as a record, but via a pointer, so no memory is involved when used.
