### ISSUE TITLE
Won't compile on Trunk FPC (error on IMUL)

### ISSUE THREAD

**Issue by regs01** [bgrabitmap/bgrabitmap#220]
Compilation stops in `bgracolorint.pas` on `operator*(const color1, color2: TColorInt65536): TColorInt65536; `
Every `imul` command have this error. 

There was also an issue ticket for FPC
https://gitlab.com/freepascal.org/fpc/source/-/issues/40399

**Comment by circular17** [comment]
Hello regs01,

Thank you for reporting the problem here. Apparently it is related to the operand size that is now expected to be specified. Does it help prefixing the address with `dword ptr `?

For example, instead of `imul [esi]` the code would be `imul dword ptr [esi]`.

Regards

**Comment by regs01** [comment]
It does compile

**Comment by circular17** [comment]
Ok, I've applied the changes on dev branch! Don't hesitate to reopen if there is another compilation problem related to asm in this unit.
