### ISSUE TITLE
Multiple package issue

### ISSUE THREAD

**Issue by lainz** [bgrabitmap/bgrabitmap#222]
Hi, I'm using BGRABitmap with Lazarus LCL. But I have a project that needed the new BGRABitmap4NoLCL.

When compiling both, issues happens. Like other projects using BGRABitmap with LCL not compiling anymore. 

The solution was removing everything with git that was not in the repo, and rebuilding lazarus.

Maybe a hint can be use different IDEs for each package? Or there's a better solution.

**Comment by circular17** [comment]
Hi Lainz,

Thanks for pointing out this issue. I've fixed the problem on `dev-brabitmap` branch. The binary output path was the same as the other package. I've changed it to explicitly include `nolcl` in the path. For example: `x86_64-darwin-nolcl-3.2.2`

Warm regards

**Comment by lainz** [comment]
Thanks for the fix.

See you.
