### ISSUE TITLE
New version of BGRABitmap (11.5.7) corrupts Lazarus - it stops seeing component icons in LRS resources

### ISSUE THREAD

**Issue by paweld** [bgrabitmap/bgrabitmap#224]
After installing BGRABitmap 11.5.7, lazarus stops seeing component icons from `LRS` resources. After rolling back to version 11.5.6, everything is OK again.

How to reproduce the problem:
- install BGRABitmap 11.5.7
- install BGRAControls 7.7

After rebuilding lazarus, there are default icons on the BGRAControls tab.
Installing BGRABitmap 11.5.6 and rebuilding lazarus causes the correct icons to appear on the component palette.

**Comment by circular17** [comment]
Hello @paweld

I don't see how BGRABitmap would affect those icons. Also, it seems you've provided a pull request for BGRAControls. Are you sure it is related to BGRABitmap?

Regards

**Comment by paweld** [comment]
Hi @circular17 
Yes, I'm sure the cause is the changes in BGRABitmap 11.5.7.
Changing resources from LRS to RES is a workaround for this problem, but a great many components still use icons in LRS and their icons don't display either.
I'll have a moment then I'll try to track down the specific fix (piece of code) that "messes up" lazarus.
Thank you for BGRABitmap, it's great. 
Have a nice day.

**Comment by paweld** [comment]
Hello @circular17 
I managed to find the commit that is causing the problem: https://github.com/bgrabitmap/bgrabitmap/commit/b9ac368e5d76a0c87aba76a9bb601d4878b15a94 
Reverse this commit solves all problems

**Comment by circular17** [comment]
[psdsgn](https://github.com/psdsgn) commented(https://github.com/bgrabitmap/bgracontrols/issues/160#issue-2026009046)
> Hello, after installing the new version of BAGRA
> -Does not display icons in the Lazarus component interface
> -after compilation it did not display icons in SpeedButton components
> -Does not display png files in the standard TImage component.
>
> Regards

**Comment by circular17** [comment]
Thank you for all the details on the issue.

It is starting to make sense to me. It would not be related to LRS resources as such but with image formats. Same goes for `TImage` and `TSpeedButton`.

I've tried with Lazarus 2.0.10 on a Windows virtual machine and all seemed fine. Same with release candidate version on MacOS.

@paweld @psdsgn @lainz
I suppose you've tested it on Windows. With which version of Lazarus?

I will have a look at the commit https://github.com/bgrabitmap/bgrabitmap/commit/b9ac368e5d76a0c87aba76a9bb601d4878b15a94 you've highlight @paweld so see if I find anything that could explain the bug.

Regards

**Comment by paweld** [comment]
Hi @circular17 
I tested on `Lazarus 3.99 trunk / FPC 3.2-fixes x86` and `Lazarus 2.2.6 / FPC 3.2.2 x64`. Both on `Windows 10 x64`. \
When I try to insert a PNG image on `TSpeedButton`, I get an error: `Cannot assign a TBGRAAnimatedGif to a TIcon.`

**Comment by circular17** [comment]
Thanks.

I have an idea on the reason why the problem happens: it would be related to the TGraphic class registration. I am preparing a fix to make sure PNG is not confused with animated GIF.

**Comment by circular17** [comment]
Other commit for this issue: a606441a26ec01b2a8f42cc6ede0044e4090cfce `Prevent conflict for PNG format`

Hi @paweld,

Thank you for your detailed investigation and feedback. Based on the insights you provided, I've identified a potential solution to the issue with component icons not displaying correctly in Lazarus after updating BGRABitmap.

The solution involves two adjustments:
- To register 'Animated PNG' with a different extension for  ('apng') which allows to differentiate them and by default use the legacy `TPortableNetworkGraphic`. This distinction should address the exception with `TSpeedButton` component.
- To encapsulate the serialization of `Animated PNG` in a separate stream. Indeed, FP image generic writer sets the stream position to 0 but but when `TPicture` is serialized in the LFM files, there's already data written in the stream (the class name of the `TGraphic`).

The changes are on the `dev-bgrabitmap` branch. Can you give it a try? This will help ensure that the solution is effective across different Lazarus and FPC versions.

Regards

**Comment by paweld** [comment]
Hi @circular17 
I checked the latest version from the `dev-bgrabitmap` branch and everything works, i.e. there are icons on the component palette, `png` images are properly handled in `TSpeedButton` and `TImage`.
I checked on:
- Windows 10, Lazarus 3.99 trunk / FPC 3.2 fixes x86
- Windows 10, Lazarus 2.2.6 / FPC 3.2.2 x64
- Debian 12, Lazarus 3.99 trunk / FPC 3.2 fixes x64

Thank you so much for the great component.

**Comment by circular17** [comment]
Hi @paweld,

It's great to hear that the latest updates from the `dev-bgrabitmap` branch have resolved the issues across different platforms. While my own testing capabilities are limited to slow VMs for Windows and Linux, I am grateful that you filled the crucial gap for real-world testing.

I'm excited to announce that version 11.5.8 is now published and should soon be available through OPM, bringing these fixes to a wider audience.

Regards
