### ISSUE TITLE
 bgramseguibitmap.pas does not compile on Windows.

### ISSUE THREAD

**Issue by fredvs** [bgrabitmap/bgrabitmap#225]
Hello.

I added a comment + fix in previous closed issue: https://github.com/bgrabitmap/bgrabitmap/issues/105#issuecomment-1836965522

(In case you did not see it ;-) )

Fre;D

**Comment by circular17** [comment]
Hello Fred,

Thank you for your comment and the fix you suggested in the previous issue #105. I have implemented the change in the latest commit #225. Given the straightforward nature of this fix, I believe it should resolve the issue. However, I would greatly appreciate your confirmation to ensure everything is functioning as expected.

Regards

**Comment by fredvs** [comment]
Hello Circular.

Thanks for the attention and the fix.

It is much better but not yet perfect.

Here, with MSEgui, there is still error at compilation (I noted it already in a previous post).

>bgraanimatedgif.pas(1043,38) Error: (5000) Identifier not found "clSilver"

If targets this line:

>copy := MemBitmap.MakeBitmapCopy(clSilver, true);

It can easy be fixed with this:

>copy := MemBitmap.MakeBitmapCopy(TColor($C0C0C0), true);

Fre;D

**Comment by circular17** [comment]
Ok I've changed this line as well.

Does it compile?

**Comment by fredvs** [comment]
Yep, compiles out-of-the-box, run apng perfectly on Unix and Windows.

Many thanks.

Fre;D
