### ISSUE TITLE
BGRABitmap and FPC 3.2-fixes

### ISSUE THREAD

**Issue by paweld** [bgrabitmap/bgrabitmap#229]
Hi, \
As of 2023-12-18, fpc 3.2-fixes includes changes to fcl-image, which until now were in the trunk verion (jpegcomn and psdcomn). \
For this reason, you need to make some changes to the code - the fix in the attachment.
[bgrabitmap.patch](https://github.com/bgrabitmap/bgrabitmap/files/13724489/bgrabitmap.patch)

**Comment by circular17** [comment]
Hi @paweld,

If I understand correctly, some changes that were only in version 3.3.1 are now in 3.2.3. I've applied the changes you suggested, and also some more that are related.

There are other checks for version 3.3.1 that may also be updated, but I don't know for sure:

_bgrabitmap/bgrareadtiff.pas_
```pascal
bgrareadtiff.pas (53,41) BGRABitmapTypes {$IF FPC_FULLVERSION>=30301}, FPReadTiff{$ENDIF};
bgrareadtiff.pas (56,24) {$IF FPC_FULLVERSION<30301}
bgrareadtiff.pas (169,22) {$IF FPC_FULLVERSION<30301}
```
_bgrabitmap/bgrawritepcx.pas_
```pascal
bgrawritepcx.pas (31,24) {$IF FPC_FULLVERSION<30301}
```
_bgrabitmap/bgrawritejpeg.pas_
```pascal
bgrawritejpeg.pas (25,26) {$IF FPC_FULLVERSION<30301}
bgrawritejpeg.pas (39,22) {$IF FPC_FULLVERSION<30301}
bgrawritejpeg.pas (217,24) {$IF FPC_FULLVERSION<30301}
```
_bgrabitmap/bgrawritebmp.pas_
```pascal
bgrawritebmp.pas (20,26) {$IF FPC_FULLVERSION<30301}
bgrawritebmp.pas (28,22) {$IF FPC_FULLVERSION<30301}
```

It doesn't prevent compilation I presume, so no need to rush for that. If you have some celebrations, that's more important!

**Comment by paweld** [comment]
> If I understand correctly, some changes that were only in version 3.3.1 are now in 3.2.3.

Yes.
> There are other checks for version 3.3.1

I have seen, but I have only applied changes, to those parts of the code that cause problems when compiling, due to the duplication of structures.

**Comment by circular17** [comment]
Yes, I understand. Maybe @maxm74 can help us here, as he added some of those `$IF` directives.

**Comment by paweld** [comment]
After Christmas, I will try to check the remaining dependencies of 3.3.1

**Comment by maxm74** [comment]
I've added the Resolution support in fpc from 3.3.1 trunk version, so before this version the Resolution support is inside the bgrabitmap. 
The other $if is in bgracontrols to check that your bgrabitmap version has resolution support.
