### ISSUE TITLE
compile error on bgrapixel.inc

### ISSUE THREAD

**Issue by maxm74** [bgrabitmap/bgrabitmap#230]
there is a compile error from line 94 to 103 on bgrapixel.inc
 A Copy/Paste mistake (i think).

**Comment by maxm74** [comment]
solved

**Comment by circular17** [comment]
Hi maxm,

Thank you for the quick fix.

In fact I really wanted to add **const** at the beginning of lines for documentation but then it can be redundant with the line that has only "const". I guess either I need to find a way to automatically add **const** in my generated documentation or to remove the first "const" line.

As I continue documenting, there might be some quirks like that but I'll keep this one in mind. As I compile on MacOS, some directives can differ so it's good to know you're checking for Windows.

Happy solstice!

**Comment by circular17** [comment]
Note: when we indicate at the beginning of the commit description the GitHub isssue number, here "#230", it adds a link here in the issue. I like it very much so I am trying to remember to think about it when typing. I invite you to try it if you haven't done already.

**Comment by maxm74** [comment]
I thought about it after I committed :-)

**Comment by circular17** [comment]
Same here! Last time, I tried to rename the commit but it added a branch merge just to do that.

<img width="785" alt="commit rename" src="https://github.com/bgrabitmap/bgrabitmap/assets/9092455/e49ab087-89e7-4463-97dc-13afffe504f3">
