### ISSUE TITLE
Error: Duplicate identifier "FResolutionUnit"

### ISSUE THREAD

**Issue by zeljkoavramovic** [bgrabitmap/bgrabitmap#232]
I have tried to comment out those line but other things are in trouble then...

Same symptoms for BGRABitmap via OPM and repo trunk.

FPC 3.2.3, Laz 3.0 i386-win32 running on Win11x64 created using FPCUpDeluxe

> Compile package BGRABitmapPack 11.5.8: Exit code 1, Errors: 3, Warnings: 4, Hints: 10
> Hint: Start of reading config file C:\Prg\Lazarus\Fixes30x32x\fpc\bin\i386-win32\fpc.cfg
> Hint: End of reading config file C:\Prg\Lazarus\Fixes30x32x\fpc\bin\i386-win32\fpc.cfg
> Verbose: Free Pascal Compiler version 3.2.3-1315-g3b45e9c5bb [2023/12/23] for i386
> Verbose: Copyright (c) 1993-2021 by Florian Klaempfl and others
> Verbose: Target OS: Win32 for i386
> Verbose: Compiling bgrabitmappack.pas
> Verbose: Compiling bgraanimatedgif.pas
> Verbose: Compiling bgraclasses.pas
> Verbose: Compiling bgragraphics.pas
> Verbose: Compiling bgrabitmap.pas
> Verbose: Compiling bgrabitmaptypes.pas
> Verbose: Compiling bgraunicode.pas
> bgraunicode.pas(1142,14) Hint: Local variable "a" of a managed type does not seem to be initialized
> bgraunicode.pas(1143,19) Warning: function result variable of a managed type does not seem to be initialized
> bgraunicode.pas(1258,19) Warning: function result variable of a managed type does not seem to be initialized
> bgraunicode.pas(1280,21) Hint: Local variable "levels" of a managed type does not seem to be initialized
> bgraunicode.pas(1281,30) Hint: Local variable "originalIndices" of a managed type does not seem to be initialized
> Verbose: Compiling bgramultifiletype.pas
> Verbose: Compiling bgrautf8.pas
> bgrautf8.pas(248,13) Note: Call to subroutine "function UTF8CodepointSize(p:PChar):LongInt;" marked as inline is not inlined
> bgrautf8.pas(10,3) Hint: Unit "BGRAClasses" not used in BGRAUTF8
> Verbose: Compiling bgrabitmaptypes.pas
> unibitmap.inc(121,5) Error: Duplicate identifier "FResolutionUnit"
> unibitmap.inc(121,20) Hint: Identifier already defined in unit FPIMAGE: fpimage.pp at line 121
> unibitmap.inc(122,5) Error: Duplicate identifier "FResolutionX"
> unibitmap.inc(122,17) Hint: Identifier already defined in unit FPIMAGE: fpimage.pp at line 122
> unibitmap.inc(123,5) Error: Duplicate identifier "FResolutionY"
> unibitmap.inc(123,17) Hint: Identifier already defined in unit FPIMAGE: fpimage.pp at line 123
> unibitmap.inc(126,14) Warning: An inherited method is hidden by "GetResolutionWidth:Single;"
> unibitmap.inc(127,14) Warning: An inherited method is hidden by "GetResolutionHeight:Single;"
> bgrabitmaptypes.pas(587,1) Verbose: There were 3 errors compiling module, stopping
> Verbose: Compilation aborted
> Verbose: C:\Prg\Lazarus\Fixes30x32x\fpc\bin\i386-win32\ppc386.exe returned an error exitcode

**Comment by circular17** [comment]
Hi @zeljkoavramovic,

This seems to be related to #229 that has been applied on `dev-bgrabitmap` branch. I invite you to try with this branch.

https://github.com/bgrabitmap/bgrabitmap/tree/dev-bgrabitmap

Regards

**Comment by zeljkoavramovic** [comment]
Thanks, but I have already somehow fixed it manually last night. I needed bgrabitmap working only because of PascalSCADA anyway.

**Comment by maxm74** [comment]
Wich version of fpc compiler use?

**Comment by circular17** [comment]
`master` branch is for FPC 3.2.2, `dev` branch normally works with more recent FPC.
