### ISSUE TITLE
Avoid WideString, use UnicodeString

### ISSUE THREAD

**Issue by Alexey-T** [bgrabitmap/bgrabitmap#234]
Rika, coder who makes good FPC patches, wrote

>Most of the applications don’t and shouldn’t use widestrings, as unicodestrings are superior.

https://gitlab.com/freepascal.org/fpc/source/-/commit/48815baef63e4eff8191d1867a56615c7719295b

but you use WideString.

![bgra-bad](https://github.com/bgrabitmap/bgrabitmap/assets/4154978/be57ee18-1bf6-47b8-859d-0035483a7c75)

**Comment by circular17** [comment]
Maybe some can be removed, but in bgraopenraster.pas the reason is to prevent a compiler warning.

**Comment by Alexey-T** [comment]
I suggest to __replace__ Widestring -> UnicodeString.

**Comment by circular17** [comment]
Looking at the definition of DOMString, it seems it has been updated to UnicodeString. So indeed this can be replace without side effect.
