### ISSUE TITLE
libwebp.pas fails to compile if -Mobjfpc was not used at compilation.

### ISSUE THREAD

**Issue by fredvs** [bgrabitmap/bgrabitmap#235]
Hello.

By default, the mode used by fpc is  **{$mode fpc}**.
But **libwebp.pas** uses some syntax that needs the mode **{$mode objfpc}**.

If you dont define at compilation **-Mobjfpc** or use a other mode, there is a error message when trying to compile **libwebp.pas**.
To fix this, just add at begin of  **libwebp.pas**,  after _unit libwebp;_ :

`{$mode objfpc}`

**Comment by circular17** [comment]
Hi Fred,

I understand, adding this directive will make it more straightforward to compile. I've done the change as you suggested.

Regards
