### ISSUE TITLE
Draw image center/cover no-repeat

### ISSUE THREAD

**Issue by lainz** [bgrabitmap/bgrabitmap#236]
Actually there is "Bitmap.StretchPutImageProportionally"

But I want as well "Bitmap.StretchPutImageCenterCoverNoRepeat" like is done with CSS.

Attached an html with css, just check the body styles.
[cover.zip](https://github.com/bgrabitmap/bgrabitmap/files/14239499/cover.zip)

**Comment by lainz** [comment]
Just resize the browser window to see the effect, the image is scaled but as well centered despite the resolution of the browser.

**Comment by circular17** [comment]
Hi Leandro,

I understand you would like the image to cover the background.

On `dev-bgrabitmap` branch, I've added the `ACover` boolean parameter to the `StretchPutImageProportionally` function. To cover the rectangle, set this parameter to `True`. This way you can use the same function with the horizontal and vertical alignment parameters as well.

Note: if the `ARect` rectangle is only part of the image, the image will extend beyond the rectangle. If you don't want this to happen, it is possible to prevent it by setting the clipping rectangle prior to the call.

Can you try it to see if that meets your need?

Regards

**Comment by lainz** [comment]
Hi, it works fine, thanks =)
