### ISSUE TITLE
crash on loading WEBP image on Windows-10 x64 (32bit EXE) when no DLL file is present (it must show nice msg about missing DLL)

### ISSUE THREAD

**Issue by CudaText-addons** [bgrabitmap/bgrabitmap#241]
my code from CudaText to load pictures, also WEBP:
```pascal
function DoPictureLoadFromFile(const AFilename: string): TGraphic;
var
  ext: string;
  ImageEx: TBGRABitmap;
  Bmp: TBitmap;
begin
  Result:= nil;
  if not FileExists(AFilename) then exit;
  ext:= LowerCase(ExtractFileExt(AFilename));

  if ext='.png' then
    Result:= TPortableNetworkGraphic.Create
  else
  if ext='.gif' then
    Result:= TGIFImage.Create
  else
  if ext='.bmp' then
    Result:= TBitmap.Create
  else
  if (ext='.jpg') or (ext='.jpeg') or (ext='.jfif') then
    Result:= TJPEGImage.Create
  else
  if ext='.webp' then
  try
    ImageEx:= TBGRABitmap.Create(AFilename);
    if not Assigned(ImageEx) then exit;
    Bmp:= TBitmap.Create;
    Bmp.PixelFormat:= pf24bit;
    Bmp.Transparent:= true;
    Bmp.SetSize(ImageEx.Width, ImageEx.Height);
    ImageEx.Draw(Bmp.Canvas, 0, 0, True);
    Result:= Bmp;
    exit;
  finally
    FreeAndNil(ImageEx);
  end
  else
    exit;

  try
    Result.LoadFromFile(AFilename);
    Result.Transparent:= true;
  except
    FreeAndNil(Result);
  end;
end;
```
when CudaText don't have libwebp32.dll in EXE dir, app crashes with AccessViolation in the line `FreeAndNil(ImageEx);`., can you see this crash?

if I copy DLL to app dir - it works.

**Comment by CudaText-addons** [comment]
if I change line `FreeAndNil(ImageEx)` to
```
    if Assigned(ImageEx) then
      FreeAndNil(ImageEx);
```
it still crashes.

**Comment by circular17** [comment]
Investingating a bit, I think that an exception would occur normally in the following procedure in `BGRAReadWebP` unit (line 36):

```pascal
procedure NeedLibWebP;
begin
  if not MyLibWebPLoaded then
  begin
    if not LibWebPLoad then
      raise exception.Create('Cannot find libwebp library ('+LibWebPFilename+')');
    MyLibWebPLoaded:= true;
  end;
end; 
```

Can you compile BGRABitmap and you project with debugging information and put a breakpoint in this procedure to see what happens?

At some point, the library is supposed to be checked with the following function in `libwebp` unit (line 554):
```pascal
function LibWebPLoaded: boolean;
begin
 Result := (LibWebPHandle <> dynlibs.NilHandle);
end;  
```

Regards

**Comment by CudaText-addons** [comment]
debugging shows going here
```
class procedure TUniversalDrawer.LoadFromFileUTF8(
  ADest: TCustomUniversalBitmap; const AFilenameUTF8: string;
  AOptions: TBGRALoadingOptions);
var
  stream: TStream;
  format: TBGRAImageFormat;
  reader: TFPCustomImageReader;
begin
  stream := TFileStreamUTF8.Create(AFilenameUTF8, fmOpenRead or fmShareDenyWrite);
  try
    format := DetectFileFormat(Stream, ExtractFileExt(AFilenameUTF8));
    reader := CreateBGRAImageReader(format);  
```

'format' here is inited. it is const 20=IFWEBP,
next 'reader' line is maybe working bad? 'reader' is not Nil but it has many Nil fileds.

**Comment by CudaText-addons** [comment]
okay, debugging stops on the `NeedLibWebP` procedure. and it runs `raise exception.create`. then debugging shows some reentering to NeedLibWebP and again raising the error. again. again. then crash.

**Comment by circular17** [comment]
Thanks for looking into this with the debugger.

Ok, so the exception is raised but somehow it doesn't propagate out of the block.

**Comment by circular17** [comment]
If I do a test project and that the libary is not here, I can see the exception popping. I am not sure why this would not happen with your program. Could be related to threading for example.

**Comment by CudaText-addons** [comment]
not to threads , but related to the fact: this func is called by Python plugin (so python engine may do some bad things?).

**Comment by circular17** [comment]
Ah I think I know.

You would need to set the variable to **nil** prior to doing the **try**:
```pascal
  begin
    ImageEx:= nil;
    try
      ...
    finally
      FreeAndNil(ImageEx);
    end
  end;
```

**Comment by CudaText-addons** [comment]
yes!! thanks! this has fixed it.

**Comment by circular17** [comment]
You're welcome.

It wasn't a bug in BGRABitmap in the end, so I've removed the bug tag.

Happy coding
