### ISSUE TITLE
-dBGRABITMAP_CORE and Canvas2D

### ISSUE THREAD

**Issue by fredvs** [bgrabitmap/bgrabitmap#244]
Hello.

I am testing the new definition **-dBGRABITMAP_CORE** in last version 11.6.
When adding that define in one of my BGRA-MSEgui project, with code like this:

`aBGRABitmap.Canvas2D.beginPath; `

there is that error at compilation:

` Error: (5038) identifier idents no member "Canvas2D"`

I  suppose it is because with **-dBGRABITMAP_CORE** and using **Canvas2D**, a unit must be added in the uses section.
I did try adding **BGRACanvas2D** but it did not help.

What do I missing?

Note that not using **-dBGRABITMAP_CORE** gives a perfect compilation and I am happy with it, but, like said before, I am also OK if I can spare few kb.

Thanks.

Fre;D

**Comment by circular17** [comment]
Hi Fred,

Indeed, when using core version, the Canvas2D (and CanvasBGRA) property are not available. You need instead to create an instance of TBGRACanvas2D (or TBGRACanvas) and use the functions it provides. The constructor takes the bitmap as parameter. 

Regards

**Comment by fredvs** [comment]
Hello Jo.

OK, thanks.
