### ISSUE TITLE
Gradient text and last version 11.6.

### ISSUE THREAD

**Issue by fredvs** [bgrabitmap/bgrabitmap#245]
Hello.

When using the previous version of BGRABitmap and compiling the test demo from here:
https://github.com/bgrabitmap/bgrabitmap/tree/master/test/test4ideu/fractal_tree

I get this:

![fractral-tree1](https://github.com/bgrabitmap/bgrabitmap/assets/3421249/862b9f33-8a39-4427-88b2-f7b4642dc864)

You may note that the vertical text has nice rainbow gradient colors.

But using last BGRABitmap version 11.6, compiling  the same code, I get that:

![fractral-tree2](https://github.com/bgrabitmap/bgrabitmap/assets/3421249/99c2310c-becf-43c1-99a8-c0eb6e1b6e2a)

You may note here that the beautiful rainbow colors are now gray. ;-(

Here the concerned code:

```
 bmp.FontFullHeight := 40;
  bmp.FontStyle := [fsBold];
  textWidth := bmp.TextSize(SampleText).cx;
  grad := TBGRAHueGradient.Create(0,0,65535,40000,[hgoRepeat,hgoPositiveDirection,hgoLightnessCorrection]);
  scan := TBGRAGradientScanner.Create(grad, gtLinear, PointF(0, bmp.Height - MarginY), PointF(0, bmp.Height - MarginY - textWidth));
  bmp.TextOutAngle(bmp.Width - MarginX - bmp.FontFullHeight, bmp.Height - MarginY, 900, SampleText, scan);
  scan.Free;
  grad.Free;
```

**Comment by circular17** [comment]
Hi Fred,

This gradient result seems to be a regression. I'll look into it.

Thank you Fred for the prompt feedback. We won't let this bug too long in the wild.

Regards

**Comment by circular17** [comment]
Hi Fred,

That's fixed on dev branch. Can you give it a try?

Cheers

**Comment by fredvs** [comment]
Yep, fixed, many thanks!
