### ISSUE TITLE
Lazarus 3.2 and fpc 3.2.2 

### ISSUE THREAD

**Issue by anderbelluno** [bgrabitmap/bgrabitmap#252]
bgrabitmap is compatible with Windows/Lazarus 3.2/fpc 3.2.2 ?
I try install using OPM, but i cant see in component pallet.

![image](https://github.com/bgrabitmap/bgrabitmap/assets/36983422/e2c00b49-27ad-4a81-b13f-549f72e01d6d)

**Comment by anderbelluno** [comment]
I needed install BGRAControls, but this don't write in documentation.
Thank you.

**Comment by circular17** [comment]
Hello @anderbelluno 

Indeed, BGRABitmap is only the drawing library. The controls are in another package. It could be a good idea to mention it in the documentation. Are you referring to the wiki?

Regards
