### ISSUE TITLE
TBCComboBox doesn't work properly In Lazarus 3.4

### ISSUE THREAD

**Issue by UrukFSP** [bgrabitmap/bgrabitmap#254]
Hi,
I've just switched from Lazarus 2.2.6 to Lazarus 3.4 environment. If I use TBCComboboxes into a non-modal forms it works as expected but in my modal forms (all showed by means of ShowModal, I mean) if I click on the array no dropdown window is opened even though the control contains the items loaded. Item change works only with left and right arrow on the keyboard. This happens under a **MacOS project**, I didn't check if Linux and Windows are affected by this issue.

Regards
Alberto Cavalli

**Comment by lainz** [comment]
Hi, that's fixed in the latest release. Plese upgrade BGRAControls to v9.0.1.5
