### ISSUE TITLE
Compilation raised exception internally

### ISSUE THREAD

**Issue by maxm74** [bgrabitmap/bgrabitmap#255]
I have this error with the last version of package (same error with bgracontrols)

 FPC 3.3.1 and Lazarus 3.99   (they are not the latest version taken from the repository)

**Comment by circular17** [comment]
Hi @maxm74 

Seems the update of the compiler have some issues. I suggest to report it to FPC compiler bugtracker.

On BGRABitmap side, if we can locate the error, we could find a workaround. Is there any indication on the position in the source code?

Regards

**Comment by fredvs** [comment]
Maybe absolutely out of the game, but did you try to compile with **-B** (build all) parameter?

**Comment by maxm74** [comment]
00004000:[156.813] (BGRASVG)  (10056) Finished loading unit BGRASVG
00004000:[156.813] (BGRABITMAPPACK) (10048) Adding dependency: BGRABITMAPPACK depends on BGRASVG
10000002:[156.813] Error: (1026) Compilation raised exception internally
10000001:[157.148] Fatal: (1018) Compilation aborted

**Comment by maxm74** [comment]
Ok solved is only a clean problem
