### ISSUE TITLE
Can't compile in Trunk

### ISSUE THREAD

**Issue by lainz** [bgrabitmap/bgrabitmap#35]
Hi, the new release can't be compiled in Lazarus Trunk 1.9 + FPC Trunk 3.1.1

BGRAMultiFileType.pas

```
function TMultiFileContainer.GetRawStringByFilename(AFilename: string
  ): RawByteString;
var
  idx: Integer;
begin
  idx := IndexOf(TEntryFilename.New(AFilename));
  if idx = -1 then
    result := ''
  else
    result := GetRawString(idx);
end;  
```
idx := IndexOf(TEntryFilename.New(AFilename));

bgramultifiletype.pas(228,47) **Error:** Only class methods, class properties and class variables can be referred with class references

```
procedure TMultiFileContainer.SetRawStringByFilename(AFilename: string;
  AValue: RawByteString);
var
  f: TEntryFilename;
begin
  f := TEntryFilename.New(AFilename);
  Add(f.Name,f.Extension,AValue,true);
end; 
```

f := TEntryFilename.New(AFilename);  

bgramultifiletype.pas(247,37) **Error:** Only class methods, class properties and class variables can be referred with class references

**Comment by circular17** [comment]
Thanks for letting me know. I have changed to a simple function EntryFilename instead of a class function (on dev branch). Does it help?

**Comment by lainz** [comment]
Hi, thanks, I will check it out!

**Comment by lainz** [comment]
FOriginals[AIndex] := TBGRALayerOriginalEntry.New(result);  

bgralayers.pas(817,62) Error: Only class methods, class properties and class variables can be referred with class references

This is in some more places.

Maybe we need to ask in the bug tracker or in the forum, to see if these changes are intentional or a bug of the compiler.

**Comment by circular17** [comment]
I suppose those are intentional change because it doesn't make sense that those functions would not be class functions. However with the previous version, the declaration of the class function is not accepted. So I suppose they have fixed that or will fix that and are trying to make things consistent. Anyway those are small changes I can make. I have changed to a simple BGRALayerOriginalEntry function. Does it compile now?

**Comment by lainz** [comment]
Ok. It compiles now =)

**Comment by circular17** [comment]
Cool. Thanks very much
