### ISSUE TITLE
PNG Arithmetic overflow error

### ISSUE THREAD

**Issue by phoenixfenix** [bgrabitmap/bgrabitmap#37]
Hello,
I have compiled the library 9.8.1 with FPC 3.0.4 and Lazarus 1.8.4 (Win10)
If I use 64 bit compiler all ok but if I use 32 bit the debugger show error message RunError 215 (Arithmetic overflow error) in BGRAReadPng.pas -> FilterUp() -> at line 1103
  
```
{$push}{$r-}
PDWord(p)^ := (((PDWord(pPrev)^ and $00FF00FF) + (PDWord(p)^ and $00FF00FF)) and $00FF00FF)
 or (((PDWord(pPrev)^ and $FF00FF00) + (PDWord(p)^ and $FF00FF00)) and $FF00FF00);
{$pop}
```

Probably there is a better implementation but this should solve the problem

```
{$IFDEF CPU32}
 TempD1,TempD2: DWord;
 TempQ: QWord;
{$ENDIF}

..

{$IFDEF CPU32}
TempQ := PDWord(pPrev)^ and $00FF00FF;
Inc(TempQ, PDWord(p)^ and $00FF00FF);
if TempQ > $FFFFFFFF then
  TempD1 := TempQ - $FFFFFFFF
else
  TempD1 := TempQ;
TempQ := PDWord(pPrev)^ and $FF00FF00;

Inc(TempQ, PDWord(p)^ and $FF00FF00);
if TempQ > $FFFFFFFF then
 TempD2 := TempQ - $FFFFFFFF
else
 TempD2 := TempQ;

PDWord(p)^ := (TempD1 and $00FF00FF) or (TempD2 and $FF00FF00);
..
```

Attached the image used for testing
![test](https://user-images.githubusercontent.com/28159966/42414522-e0774a6a-8236-11e8-9f97-eb903d63e3e6.png)

 Thanks

**Comment by circular17** [comment]
Hello,

I suppose the overflow checks are enabled in the package debug options. It is expected that there would be an overflow indeed but it can be safely ignored.

Does it help to add {$q-} directive just after {$r-} ?

Regards

**Comment by phoenixfenix** [comment]
Hello.

Yes, this solution with {$q-} is perfect

  Thank you!!
