### ISSUE TITLE
FontOrientation does not work on NoGUI 

### ISSUE THREAD

**Issue by circular17** [bgrabitmap/bgrabitmap#38]
Copied from https://sourceforge.net/p/lazpaint/bugs/36/

Hi, Tried this code on GUI and it works, but the FontOrientation on NoGUI does not work... what would it be?

var
bmp: TBGRABitmap;
FFontCollection: TFreeTypeFontCollection;
begin
FFontCollection := TFreeTypeFontCollection.Create;
FFontCollection.AddFile('c:\windows\fonts\arial.ttf');
FFontCollection.AddFile('c:\windows\fonts\ITCBLKAD.TTF');
SetDefaultFreeTypeFontCollection(FFontCollection);
bmp := TBGRABitmap.Create(400, 200);
bmp.FontOrientation := 200;
bmp.FontName := 'Arial';
bmp.FontHeight := bmp.Height div 5;
bmp.FillEllipseAntialias(200, 100, 190, 90, BGRA(26, 22, 169));
with bmp.FontPixelMetric do
bmp.TextOut(bmp.Width / 2, bmp.Height / 2 - (CapLine + Baseline) / 2,
'Too little too late!', BGRA($FF, $AA, $CC), taCenter);
bmp.FontOrientation := -200;
bmp.FontAntialias := true;
bmp.FontName := 'BlackAdder itc';
bmp.Canvas.Pen.Color := $FF00;
bmp.Canvas.Brush.Color := $FF00AA;

bmp.Canvas.Ellipse(bmp.Width div 4, 20, bmp.Width - bmp.Width div 4, 100);
bmp.TextOut(bmp.width / 2, 10,'Empana', $FF0000, taCenter);
bmp.SaveToFile('Arial.png');
bmp.Free;
FFontCollection.Free;
end;

**Comment by Rumcajs47** [comment]
I have run in this to, console app (no gui) :

the default TextOut functions works, but using TextOutAngle or FontOrientation fails -> no output at all.

archlinux
KDE
Lazarus 1.8.4, FPC 3.0.4 x86_64-linux-qt5
BGRABitmap v9.8.1

**Comment by circular17** [comment]
Indeed rotating the image could do. Note that there would not be ClearType effect, only antialiased. That's one of the reason why I haven't done a patch about it. But maybe it would be better than nothing?

**Comment by circular17** [comment]
Here is a function you can use to do that. It needs BGRATransform in the uses clause.

It draws the text without rotation in a temporary bitmap and then renders it with the appropriate angle.

Regards

```
//uses BGRATransform
procedure TForm1.TextOutAnglePatch(ADest: TBGRABitmap;
  x, y: single; orientationTenthDegCCW: integer;
  s: string; c: TBGRAPixel; AAlign: TAlignment; AResampleFilter: TResampleFilter);
const orientationToDeg = -0.1;
var
  temp: TBGRABitmap;
  coord: TPointF;
  angleDeg: single;
begin
  temp := TBGRABitmap.Create;
  ADest.CopyPropertiesTo(temp);
  temp.FontOrientation := 0;
  with temp.TextSize(s) do
    temp.SetSize(cx,cy);
  temp.FillTransparent;
  temp.TextOut(0,0, s, c);

  angleDeg := orientationTenthDegCCW * orientationToDeg;
  coord := PointF(x,y);
  case AAlign of
  taRightJustify: coord -= AffineMatrixRotationDeg(angleDeg)*PointF(temp.Width,0);
  taCenter: coord -= AffineMatrixRotationDeg(angleDeg)*PointF(temp.Width,0)*0.5;
  end;

  ADest.PutImageAngle(coord.x,coord.y, temp, angleDeg, rfBox);
  temp.Free;
end;
```

**Comment by circular17** [comment]
Oops I clicked close but it is not closed yet.

**Comment by lainz** [comment]
Ok, is better than nothing, but
when I have time I will try to test.

**Comment by Rumcajs47** [comment]
Yeah thats a good idea guys, thank you, hope the TextOutAnglePatch function works in a console app to, gone test it later.

**Comment by circular17** [comment]
Patch published in dev branch :-)
