### ISSUE TITLE
Missing LCLPlatformDef unit in BGRAText.pas uses.

### ISSUE THREAD

**Issue by mohsenti** [bgrabitmap/bgrabitmap#4]
Hi,
I try to compile BGRABitmap with FPC trunk and Lazarus trunk that compile failed with undefine lpNoGUI error and after add LCLPlatformDef to BGRAText.pas uses error gone.

**Comment by lainz** [comment]
I already know about this. In my opinion, that unit should be added when Lazarus 1.8 get released, else 1.6 users will have problems.

This was discussed in the online package manager thread in the forum, the conclusion was not to add the unit until 1.8 get released.

**Comment by mohsenti** [comment]
You can using lazarus version const ( LCL_FULLVERSION ) from  lazarus/lcl/lclversion.pas with #ifdef.

**Comment by lainz** [comment]
Already discussed in the forum, please read all post from this point:
http://forum.lazarus.freepascal.org/index.php/topic,34297.msg232525.html#msg232525

**Comment by mohsenti** [comment]
I solve this problem with moving lclplatformdef uses under implemention.

```pascal implementation
uses GraphType, Math, BGRABlend, BGRAUTF8{$IF lcl_fullversion >= 1070000}, lclplatformdef{$ENDIF} ;
```

The above code work fine.

**Comment by lainz** [comment]
Thankyou for solving this, tested under 1.6 and works fine too. I don't know if @circular17 is notified about this bug, he is the one that makes bgrabitmap. I will notify he about this and I think it will be solved when he has some free time. And happy new year.

**Comment by mohsenti** [comment]
Thank you @lainz; Happy new year too.

**Comment by circular17** [comment]
Thanks for the feedback. I applied it on master and dev.
