### ISSUE TITLE
BGRACanvas2D.FillStrokePoly

### ISSUE THREAD

**Issue by pfradin** [bgrabitmap/bgrabitmap#41]
Une erreur à  signaler dans le fichier BGRACanvas2D.pas, dans le corps de la procédure TBGRACanvas2D.FillStrokePoly, on trouve l'intruction
multi.FillMode :=  fmWinding;
ce qui fait que le mode fmAlternate est systématiquement ignoré, 
en modifiant cette instruction en :
multi.FillMode := fillmode;
ceci règle le problème.

PS : un message dans ce sens a été posté dans le forum TeXgraph.

pfradin

**Comment by circular17** [comment]
Merci pour l'info. J'ai corrigé le problème dans la branche dev en faisant que le FillMode est toujours utilisé pour le remplissage mais que le contour est toujours en fmWinding.

```
procedure TForm1.FormPaint(Sender: TObject);
var
  p: TBGRAPath;
  bmp: TBGRABitmap;
  b: TBGRACustomBitmap;
begin
  p := TBGRAPath.Create;
  p.moveTo(40,180);
  p.lineTo(200,20);
  p.arc(200,180, 160, -Pi/2, 0, false);
  p.closePath;
  p.moveTo(200,50);
  p.lineTo(330,120);
  p.lineTo(200,150);
  p.closePath;

  bmp := TBGRABitmap.Create(ClientWidth,ClientHeight, BGRAWhite);

  bmp.HorizLine(0,100,400, CSSSilver, dmSet);

  b := bmp.CreateBrushTexture(bsFDiagonal, BGRABlack, BGRAPixelTransparent);

  bmp.FillMode:= fmAlternate;
  bmp.DrawPath(p, b, 10, CSSCyan);
  b.Free;

  bmp.Draw(Canvas,0,0);
  bmp.Free;
end;
```

![strokeoverfill](https://user-images.githubusercontent.com/9092455/43772411-4f3a9880-9a42-11e8-839d-5e8a4036827a.png)
