### ISSUE TITLE
LoadFromResouce methods for SVG

### ISSUE THREAD

**Issue by Alexey-T** [bgrabitmap/bgrabitmap#51]
TCustomIcon (see lcl/graphics.pp) has methods

    procedure LoadFromResourceName(Instance: THandle; const ResName: String); override;
    procedure LoadFromResourceID(Instance: THandle; ResID: PtrInt); override;
    procedure LoadFromResourceHandle(Instance: THandle; ResHandle: TFPResourceHandle); virtual;

they are needed here for SVG too.
For ex, on Lazarus forum user "fatmonk" wrote

>However, the test project only reads from a file. I'd like to include the SVG(s) with the executable. I'll play some more, but ideally I'd be able to include the XML of the SVG directly in my project and create the in-UI image from that - that would even allow me to manipulate things like the colours in the graphic on the fly...

**Comment by circular17** [comment]
Indeed, I was also thinking about adding LoadFromResource methods in general in BGRABitmap. For now what you can do is retrieve the stream of the resource:
```
uses LResources;

function GetResourceStream(AFilename: string): TLazarusResourceStream;
var
  ext: RawByteString;
begin
  ext := UpperCase(ExtractFileExt(AFilename));
  if (ext<>'') and (ext[1]='.') then Delete(ext,1,1);
  result := TLazarusResourceStream.Create(ChangeFileExt(AFilename,''), pchar(ext));
end; 

begin
  ...
  stream := GetResourceStream('image.svg');
  svg.LoadFromStream(stream);
  stream.Free;
  ...
end;
```

**Comment by circular17** [comment]
Resource support added in v9.9.3 (LoadFromResource function)
