### ISSUE TITLE
BGRATextBidi

### ISSUE THREAD

**Issue by lainz** [bgrabitmap/bgrabitmap#53]
Hi, with FPC trunk and Lazarus trunk I can't compile BGRABitmap.

bgratextbidi.pas(229,67) Error: Only static methods and static variables can be referenced through an object type

bgratextbidi.pas(331,66) Error: Only static methods and static variables can be referenced through an object type

bgratextbidi.pas(389,61) Error: Only static methods and static variables can be referenced through an object type

bgratextbidi.pas(1585,74) Error: Only static methods and static variables can be referenced through an object type

bgratextbidi.pas(1589,74) Error: Only static methods and static variables can be referenced through an object type

**Comment by lainz** [comment]
Hi, here an user posted a solution for this
https://forum.lazarus.freepascal.org/index.php/topic,43847.msg307556.html#msg307556

**Comment by circular17** [comment]
Ok. I added the static keyword as suggested.
