### ISSUE TITLE
compilation error in Lazarus

### ISSUE THREAD

**Issue by phampl65** [bgrabitmap/bgrabitmap#55]
When I compile BGRAbitmap4nogui in Lazarus, I get following error in BGRABitmapTypes.pas line 1165

`
const

  ResourceTypes: array[1..7] of TResourceType =
   ((ext: 'CUR'; code: RT_GROUP_CURSOR),   // all these RT... constants are unknown
    (ext: 'BMP'; code: RT_BITMAP),
    (ext: 'ICO'; code: RT_GROUP_ICON),
    (ext: 'DAT'; code: RT_RCDATA),
    (ext: 'DATA'; code: RT_RCDATA),
    (ext: 'HTM'; code: RT_HTML),
    (ext: 'HTML'; code: RT_HTML));`

Those constants are defined in BGRAWinresource which is not "use"d here. If I "use" it in implementation part, there is another error at the same place:

> bgrabitmaptypes.pas(1165,39) Error: Incompatible types: got "ShortInt" expected "PChar"

**Comment by circular17** [comment]
In theory you can draw text with BGRABitmap4nogui. See example:
https://github.com/bgrabitmap/bgrabitmap/tree/master/test/test4other
(you need to include arial.ttf to provide a base font)

On my computer, it compiles fine. I am wondering what version of Lazarus you have?

**Comment by circular17** [comment]
No response
