### ISSUE TITLE
Please add version number as a constant in the package.

### ISSUE THREAD

**Issue by winni-bartnick** [bgrabitmap/bgrabitmap#57]
I need a version number inside a BGRA unit. 
Reason: To write some code like:

--------------------------------snip--------------------------------

const fpcVersion = {$I %FPCVERSION%};
var s : string;
 
begin
s := 'Made with' + lineEnding +
       'fpc version '+ fpcVersion + LineEnding+
       'Lazarus  version '+ LCLVersion + LineEnding +
       'BGRA Version ' + ??BGRAVersion??;
showMessage (s);
end;    
 
-----------------------------snap---------------------------

Thanx Winni

**Comment by circular17** [comment]
Good idea. Though I am wondering how to retrieve it from package version.

**Comment by circular17** [comment]
That's done in dev branch.

In BGRABitmapTypes there is constant BGRABitmapVersion and function BGRABitmapVersionStr which formats it.

**Comment by circular17** [comment]
Here is how it looks:
```
const
  BGRABitmapVersion = 9090300;  // that means 9.09.03.00

  function BGRABitmapVersionStr: string;  // which returns 9.9.3
```
