### ISSUE TITLE
Error writing

### ISSUE THREAD

**Issue by ClaudioYa** [bgrabitmap/bgrabitmap#6]
Hello,

Congratulations for your excellent project. I notice to you for a little error in this unit. In line 1379 writed "FFlipX := not FFlipY;" but this correct code is "FFlip**Y** := not FFlipY;".

The Unit is "bgrabitmap/bgrabitmap/bgraopengl.pas".

Thank you!

**Comment by circular17** [comment]
Thanks for the feedback. That's fixed in the development branch and will be in next release.
