### ISSUE TITLE
There are two units with the same name.

### ISSUE THREAD

**Issue by svgest** [bgrabitmap/bgrabitmap#61]
I have installed Lazarus V2.0.2, installed some packages, also the newest bgrabitmap. I'm trying to compile a project created with Lazarus v1.6.4 and I get the following error:
There are two units with the same name:
1.
"O:\Lazarus\bgrabitmap-9.9.4\b.....\bgraanimatedgif.pas" from BGRABitmapPack 9.9.4
2.
"O:\Lazarus\bgrabitmap-9.9.4\b.....\bgraanimatedgif.pas" from BGRABitmapPack4NoGUI 9.9.4

I have tried to deinstall some packages but then I get errors on rebuilding Lazarus. 
So how can I solve this error?
Thanks

**Comment by lainz** [comment]
Just don't install both packages at the same time with the same lazarus.
