### ISSUE TITLE
Error compiling in trunk

### ISSUE THREAD

**Issue by lainz** [bgrabitmap/bgrabitmap#62]
Hi, with trunk FPC I cant compile latest dev bgrabitmap due to an FPC internal error, tested on macOS, and if I remember correctly as well on Windows.

FillPolyAntialias(GetInternalPen.ComputePolyline([PointF(x1,y1),PointF(x2,y2)],APenWidth,c), b);

GetInternalPen is marked with red. unibitmapgeneric.inc(942,21) Error: Internal error 2015052501

As well I can't compile the bgrabitmap master version too, on macOS.

lcvectororiginal.pas(191,15) Error: There is no method in an ancestor class to be overridden: "Render(TBGRABitmap;TPoint;TAffineMatrix;Boolean);"

9.9.3 is the latest version working on macOS. Sorry I've not tested it correctly the last time on macOS to report.

**Comment by circular17** [comment]
Does it help to put GetInternalPen in local variable first? Like: 
```
p := GetInternalPen;
FillPolyAntialias(p.Compute...
```

**Comment by lainz** [comment]
That works. Thanks. I've applied the fix and did the commit. But there are more bugs now I can compile this new stuff, I will report in other issue. Tested on Windows, I will test later to see if it works on macOS.

**Comment by lainz** [comment]
On macOS working fine too.

**Comment by lainz** [comment]
The other bug is on bgracontrols, please dont release the new version 10 until we found a solutionhttps://github.com/bgrabitmap/bgracontrols/issues/46

**Comment by circular17** [comment]
Ok let's have a look at it
