### ISSUE TITLE
Error: External SIGSEGV

### ISSUE THREAD

**Issue by phoenixfenix** [bgrabitmap/bgrabitmap#66]
Hello,
I encountered a problem using TDTAnalogClock
(I don't know if the component should be updated or it is a bug on library)

![error](https://user-images.githubusercontent.com/28159966/60814992-f7702900-a196-11e9-8e9b-a9f6ca225d13.jpg)

Configuration:
Windows 10 64bit
Lazarus 2.0.2 FPC 3.0.4 64bit
bgrabitmap and bgracontrols libraries: latest "master" versions of today

always using Lazarus 64bit and compiling for i386 I get the same result

the only additional information is that the problem is not present before the commit:
Jun 04, 2019
"deriving TBGRACustomBitmap from TGenericUniversalBitmap"

I enclose the small test where just press the button and wait for the timing. The error occurs simultaneously with the update.

[test.zip](https://github.com/bgrabitmap/bgrabitmap/files/3368605/test.zip)

**Comment by lainz** [comment]
Same error I had in one project with TBCButton
https://github.com/bgrabitmap/bgracontrols/issues/46

**Comment by phoenixfenix** [comment]
Ok thanks, I hadn't seen this. So I don't have to launch the computer .. (^ _ ^). 
The "test" that I have attached is very minimal so maybe it can help?
It seems so much a memory violation on pointers. Usually they are difficult bugs that show "effects" on other parts like the GUI (I hope it is not the case, I have bad memories).
I didn't check but I saw some commits on the assembler code ..

NOTE1: even if I delete the "not working if block" code it stops elsewhere.
`"pDest ^: = PBGRASolidBrushFixedData (AFixedData) ^. BGRA;" row 147 unit BGRABlend`
NOTE2: if I remove the TPanel and with this change
 
`DTAnalogClock1:= TDTAnalogClock.Create (Self);
DTAnalogClock1.Left:= 24;
DTAnalogClock1.Top:= 80;
DTAnalogClock1.Width:= 180;
DTAnalogClock1.Height:= 150;
DTAnalogClock1.Parent:= Self;`

has the same behavior (if I don't provide a position or use "alClient" the error occurs when the form appears)

**Comment by lainz** [comment]
Thanks for the demo, effectively it shows the bug, is something that I was not able to provide to circular, so he can test as well in his machine.

**Comment by circular17** [comment]
I will have a look

**Comment by circular17** [comment]
Ok I think I found the problem. It was related to freeing the bitmap handle. I fixed that on the dev branch.

Does it work for you as well now?

**Comment by phoenixfenix** [comment]
I confirm that now it works. Thank you!
