### ISSUE TITLE
SVG problem

### ISSUE THREAD

**Issue by phoenixfenix** [bgrabitmap/bgrabitmap#7]
Hello,
Thanks for your work!!!
I attach the source to test the problem.
In Test1() everything works but there is a memory leak while in Test2() the application closes.
Use: Windows 10 64bit and Lazarus 1.6.4 64 bit FPC 3.0.2
[TEST SVG.zip](https://github.com/bgrabitmap/bgrabitmap/files/965293/TEST.SVG.zip)

 Thanks

**Comment by circular17** [comment]
Thanks for posting the test program. I fixed it on the development branch.

**Comment by phoenixfenix** [comment]
I just tested and works: thanks !!!
