### ISSUE TITLE
Range check error when create marble texture

### ISSUE THREAD

**Issue by rchastain** [bgrabitmap/bgrabitmap#74]
Hello Johann!

Do you remember the marble texture that you provided to me for my chess program?
With the latest BGRABitmap version, the creation of the texture fails.
```
An unhandled exception occurred at $00000000007A75CF:
ERangeError: Range check error
  $00000000007A75CF line 518 of ../libraries/bgrabitmap/bgrafilterblur.pas
  $00000000007A7FB1 line 589 of ../libraries/bgrabitmap/bgrafilterblur.pas
  $000000000070564C line 1061 of ../libraries/bgrabitmap/universaldrawer.pas
  $00000000004EA29B line 1705 of ../libraries/bgrabitmap/unibitmap.inc
  $00000000004E9F27 line 1685 of ../libraries/bgrabitmap/unibitmap.inc
  $00000000005074A7 line 1903 of ../libraries/bgrabitmap/bgracustombitmap.inc
  $0000000000694840 line 1106 of ../libraries/bgrabitmap/bgragradients.pas
  $000000000054BDB5 line 81 of images.pas
```
Here is line 81 of image.pas:
```
function CreateMarbleTexture(tx, ty: integer): TBGRABitmap; overload;
var
  colorOscillation: integer;
  p: PBGRAPixel;
  i: integer;
begin
  WriteLn('CreateMarbleTexture ', tx, ', ', ty);
  result := CreateCyclicPerlinNoiseMap(tx, ty, 1, 1, 1); // line 81
```
With an older version of the library, the same code works.
Tell me if you need more information or if you need a test program.
Regards.
Roland

**Comment by circular17** [comment]
Hello Roland,

So the range error occurs on this line?
`shift := min(ceil((maxRadius-8)/2), floor(minRadius));`

Does it help to change it to that?
`shift := max(0,min(ceil((maxRadius-8)/2), floor(minRadius)));`

Regards,

Johann

**Comment by rchastain** [comment]
Thank you for your fast answer. Yes, it works with that modification.
Bravo !
