### ISSUE TITLE
Compile error with Darwin

### ISSUE THREAD

**Issue by rphoover** [bgrabitmap/bgrabitmap#76]
There are a couple of variables that are not defined for Darwin in the TBGRAQtBitmap.DataDrawOpaque method.  Simply add the following before "begin" for the method:
  {$IFDEF DARWIN}
  x, y: integer;
  {$ENDIF}

With that minor fix, the code compiles on Darwin.

**Comment by circular17** [comment]
Thanks for the feedback. 

Oops I just realized I made a release without that fix.

Anyway, I just pushed a change on the dev branch. In fact I've put all the variables inside the IFDEF.

Does it solve the problem?

Regards
