### ISSUE TITLE
Dynamic loading of libraries.

### ISSUE THREAD

**Issue by fredvs** [bgrabitmap/bgrabitmap#78]
Hello.

If Lainz is too busy, if you want, I can do the translation of your Pascal headers into dynamic loading of the libraries.

Fre;D

**Comment by circular17** [comment]
Sure. You're talking about libwebp I suppose?

**Comment by fredvs** [comment]
Yes.
Does bgrabitmap use other external libraries?
If yes, I may it do too.

**Comment by circular17** [comment]
You're help is very welcome.
Nope, that would be the first external library.
I've added dcraw in LazPaint though I think it is a command line program only. Basically I plugged the pipes and I don't see any other way.

**Comment by fredvs** [comment]
OK.

**Comment by fredvs** [comment]
Do you know where I may download precompiled webp.so library for Linux?
In their download page, they give only webp.a static library.

If somebody did already compile it for Linux, It would be nice to use this one.
Otherwise, asap, I will (try to) compile webp.so from scratch.

**Comment by fredvs** [comment]
I did try your demo but get this error message:

Compilation du projet - Mode : Debug - Cible : bgrawebptest : Code de sortie 1 - Erreurs : 8
bgrawebp.pas(46,63) Error: Identifier idents no member "DataByte"
bgrawebp.pas(46,78) Error: Identifier idents no member "RowSize"
bgrawebp.pas(46,94) Error: Identifier idents no member "RowSize"
bgrawebp.pas(48,63) Error: Identifier idents no member "DataByte"
bgrawebp.pas(48,78) Error: Identifier idents no member "RowSize"
bgrawebp.pas(48,94) Error: Identifier idents no member "RowSize"
bgrawebp.pas(64,36) Error: Identifier idents no member "DataByte"
bgrawebp.pas(67,36) Error: Identifier idents no member "DataByte"

**Comment by circular17** [comment]
I suppose you need a more recent version of BGRABitmap

**Comment by fredvs** [comment]
OK, I did upgrade, now this:

`bgrabitmaptypes.pas(1426,15) Error: Identifier not found "LazarusResources"`

Sorry but I do not know well Lazarus and how to tune it.
So I will finish the Pascal header but, sadly, I will not be able to test it.

Fre.D

**Comment by lainz** [comment]
Hi thanks for helping. As I commented in the forum I'm a bit sick with sinusitis and headaches. I appreciate a lot your help.

**Comment by fredvs** [comment]
Hello Lainz.
I hope you will feel better soon.
Dont worry about the dynamic loader, I already did it.
There is a pull-request.

I did not test it with the demo yet.
For this I have to find time to install last Lazarus release.

Fre;D

**Comment by fredvs** [comment]
Hello.

Here library `libwebp.so` for Linux 64 bit freshly compiled:
[libwebp.zip](https://github.com/bgrabitmap/bgrabitmap/files/3822162/libwebp.zip)

**Comment by fredvs** [comment]
OK, done in https://github.com/bgrabitmap/webp
