### ISSUE TITLE
bgrabitmaptypes.pas(104,1) Error: Internal error 200611031

### ISSUE THREAD

**Issue by lainz** [bgrabitmap/bgrabitmap#92]
Hi, I'm using FPC Trunk and Lazarus Trunk, I grabbed the latest bgrabitmap dev, when I try to compile any program wich uses BGRABitmap it displays this error:

bgrabitmaptypes.pas(104,1) Error: Internal error 200611031

I think is an FPC bug, but I'm not sure what to do.

**Comment by circular17** [comment]
That's line 104 of BGRABitmapTypes? I don't see anything particular there.

I suggest to report it on FPC bugtracker.

**Comment by lainz** [comment]
Ok, I switched back to master branch and it works.
