### ISSUE TITLE
TextSize function does not account for line breaks

### ISSUE THREAD

**Issue by josiasmat** [bgrabitmap/bgrabitmap#96]
When I use TBGRABitmap.TextSize function with a string that has line breaks, the function calculates the size as if the string had only one line, ignoring the line breaks. 

Well, this is the same behaviour as the TextOut procedure. So, maybe should it have TextMultilineSize function?

Attached a sample Lazarus projetct. Using bgrabitmap version 10.8.1.

[BgraTextSizeTest.zip](https://github.com/bgrabitmap/bgrabitmap/files/4471257/BgraTextSizeTest.zip)

**Comment by circular17** [comment]
That’s a good point.

**Comment by circular17** [comment]
In fact, you can get TextSize with line breaks by specifying the maximum width parameter:
`    function TextSize(sUTF8: string; AMaxWidth: integer): TSize; override;`

Though you would have a paragraph spacing of zero.

**Comment by josiasmat** [comment]
I wrote the following two functions to measure multi-line strings. The first takes a TStrings as argument; the other takes a string.
```
function BgraTextMultilineSize(const ABgraBitmap: TBgraBitmap;
  const AStrings: TStrings; const AParagraphSpacing: Single = 0.0): TSize;
var TextLineSize: TSize;
    i: Integer;
begin
  Result := Size(0, 0);
  if AStrings.Count > 0 then
  begin
    for i := 0 to AStrings.Count-1 do
    begin
      TextLineSize := ABgraBitmap.TextSize(AStrings[i]);
      Result := Size( Max(Result.Width,TextLineSize.Width),
                      Result.Height + TextLineSize.Height);
    end;
    Inc(Result.cy, Round(AParagraphSpacing*i));
  end;
end;

function BgraTextMultilineSize(const ABgraBitmap: TBgraBitmap;
  const AStr: String; const AParagraphSpacing: Single = 0.0): TSize;
var TmpStrings: TStringList;
begin
  if AStr.IsEmpty then Exit( Size(0,0) );
  TmpStrings := TStringList.Create();
  TmpStrings.Text := AStr;
  Result := BgraTextMultilineSize(ABgraBitmap, TmpStrings, AParagraphSpacing);
  TmpStrings.Free();
end;
```

But it would be nice if this functionality was integrated into the library.

**Comment by circular17** [comment]
I see. So you would like to be able to have a non zero paragraph spacing I suppose.

Alright then.

**Comment by circular17** [comment]
What about this signature?
`function TBGRABitmap.TextSizeMultiline(sUTF8: string; AMaxWidth: single = EmptySingle; AParagraphSpacing: single = 0): TSize;`

**Comment by circular17** [comment]
Done on dev branch
