### ISSUE TITLE
DeleteFileUTF8 not found when not using LCL

### ISSUE THREAD

**Issue by suve** [bgrabitmap/bgrabitmap#98]
`bgrabitmap/bgrautf8.pas` specifies
```
function DeleteFileUTF8(Const FileName : string): boolean;
```
in its interface section (line 61). There is an implementation of the function at line 175, however, it is subject to the `{$IFDEF BGRABITMAP_USE_LCL}` compiler switch from line 112. As a result, when compiling without LCL, the build fails due to missing function implementation.

**Comment by circular17** [comment]
Indeed, this was fixed in the latest release (10.8.1).

**Comment by suve** [comment]
Doesn't seem so to me? The line numbers I gave are from the current GitHub `master`.

**Comment by circular17** [comment]
Oh you're right that's not on master branch indeed.

That's on dev branch.

Line 294 of bgrautf8.pas:
```
function DeleteFileUTF8(const FileName: string): boolean;
begin
  result := DeleteFile(UTF8ToSys(FileName));
end;         
```
https://github.com/bgrabitmap/bgrabitmap/blob/dev-bgrabitmap/bgrabitmap/bgrautf8.pas

**Comment by circular17** [comment]
will be in next release
